### ISSUE TITLE
Can't start a workspace by factory on dogfooding instance

### ISSUE THREAD

**Issue by svor** [eclipse/che#21421] opened 2022-05-24 15:40 UTC
### Describe the bug

It is not possible to start any workspace by using factory.

The error is: Failed to resolve a devfile. Failed to request factory resolver: There is an error happened when communicate with SCM server. Error message: Unexpected status code 401 (GET https://api.github.com/user) 401

### Che version

next (development version)

### Steps to reproduce

1. Try to start the workspace by https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#/https://github.com/crw-samples/web-nodejs-sample/tree/che-qe-no-extensions

### Expected behavior

The workspace should start

### Runtime

OpenShift

### Screenshots

![screenshot-che-dogfooding apps che-dev x6e0 p1 openshiftapps com-2022 05 24-18_37_14](https://user-images.githubusercontent.com/1271546/170076359-1b8d163b-ce73-4434-a064-11ac01b334bb.png)

### Installation method

OperatorHub

### Environment

Linux

**Comment by benoitf** [comment] 2022-05-24 16:04
you should remove your ‘personal-access-token’ secret from your user namespace

**Comment by azatsarynnyy** [comment] 2022-05-24 16:34
Removing the `personal-access-token` secret fixed the problem for me.
I'm closing this one within the issue triage process. Feel free to reopen if the problem is still relevant.

**Comment by ibuziuk** [comment] 2022-05-25 14:54
if this error occurs there should be a clear error message with the instructions on how to fix it. In the ideal case we should prevent this error from occurring and renew the token if expired

**Closed as completed** 2022-07-13 12:17 UTC
Labels: kind/bug, sprint/current
