### ISSUE TITLE
GitHub Pull Request Plugin is failing to start on Developer Sandbox

### ISSUE THREAD

**Issue by ibuziuk** [eclipse/che#20911] opened 2021-12-10 08:55 UTC
### Describe the bug

GitHub Pull Request Plugin is failing to start on Developer Sandbox

### Che version

7.38

### Steps to reproduce

Reproducer https://github.com/eclipse/che-docs/blob/master/devfile.yaml

### Expected behavior

GitHub Plugin starts correctly

### Runtime

OpenShift

### Screenshots

![image](https://user-images.githubusercontent.com/1461122/145545683-ec8b4299-59d0-4dc8-a606-5dbabe5fceba.png)

### Installation method

OperatorHub

### Environment

Dev Sandbox (workspaces.openshift.com)

**Comment by ibuziuk** [comment] 2021-12-10 08:55
@vinokurig @svor could you please take a look?

**Comment by ibuziuk** [comment] 2021-12-10 08:57
ok, looks like it is addressed already as part of https://github.com/eclipse/che/issues/20689
@svor the fix is expected in CRW 2.14 right?

**Comment by svor** [comment] 2021-12-10 10:26
@ibuziuk right, it's for 2.14 https://github.com/redhat-developer/codeready-workspaces/pull/633

**Comment by svor** [comment] 2021-12-10 10:32
duplicate of https://github.com/eclipse/che/issues/20689

**Closed as completed by svor** 2021-12-10 10:32 UTC
Labels: kind/bug, severity/P1, area/plugins
