### ISSUE TITLE
Upgrade devfile on existing workspace no more working on 7.67.0

### ISSUE THREAD

**Issue by disaster37** [eclipse/che#22242] opened 2023-05-30 07:58 UTC
### Describe the bug

Since we can't update devfile from eclipse che UI, we doesn't found the way to do that.
I read wome issue about the new way to do that. It seems to update the local devfile.yaml after starting workspace and then run task `Eclipse Che: Restart workspace from local devfile`. But the task failed with message:
```
Can not restart the workspace from the local devfile: Error: Request failed with status code 500
```

I doesn't found any log about this error on eclipse che server container...

### Che version

7.67@latest

### Steps to reproduce

Instal the eclipse che server on k8s.
Start new workspace from git repository with devfile.yaml on root on repo.
After workspace is started, run the task `Eclipse Che: Restart workspace from local devfile`.

### Expected behavior

It restart the workspace with from new devfile.yaml

### Runtime

Kubernetes (vanilla)

### Installation method

chectl/latest

### Environment

Linux

**Comment by RomanNikitenko** [comment] 2023-05-30 10:46
I tested it on 2 different instances and I was not able to reproduce the problem, so maybe there is something specific to an environment or a devfile...

**Comment by disaster37** [comment] 2023-05-30 12:10
On console, I look this:
![pWMo4cFDgs](https://github.com/eclipse/che/assets/10331073/f2c7265a-a571-4e74-bbd0-130a119e11b5)

**Comment by RomanNikitenko** [comment] 2023-05-31 07:49
@disaster37 
thank you for the info
I have a guess about the cause of the problem, will investigate it more deeply.

**Comment by RomanNikitenko** [comment] 2023-05-31 09:47
I prepared a draft PR to check my guess: https://github.com/che-incubator/che-code/pull/236

@disaster37 
could you help me with testing?
[This test-repo](https://github.com/RomanNikitenko/web-nodejs-sample/tree/fix-restart-from-devfile) contains a [reference to the image ](https://github.com/RomanNikitenko/web-nodejs-sample/blob/a1335f91798efc4c83570a2f37ce5ad825726b76/.che/che-editor.yaml#L33) that was built for my draft pull request.

thanks in advance!

**Comment by disaster37** [comment] 2023-05-31 12:35
Hi, 
How I can help you ? What I need to do to test you image ?

**Comment by RomanNikitenko** [comment] 2023-05-31 12:37
- please create a workspace using this repo: https://github.com/RomanNikitenko/web-nodejs-sample/tree/fix-restart-from-devfile. It brings an editor/image with my fix.
- try to reproduce the problem

**Comment by disaster37** [comment] 2023-05-31 12:48
Same issue

```
workbench.web.main.js:94 [Extension Host] Something went wrong for the 'Restart From Local Devfile' action: Error: Request failed with status code 500
y @ workbench.web.main.js:94
$logExtensionHostMessage @ workbench.web.main.js:1555
N @ workbench.web.main.js:1555
M @ workbench.web.main.js:1555
H @ workbench.web.main.js:1555
G @ workbench.web.main.js:1555
(anonymous) @ workbench.web.main.js:1555
invoke @ workbench.web.main.js:90
deliver @ workbench.web.main.js:90
fire @ workbench.web.main.js:90
fire @ workbench.web.main.js:561
E @ workbench.web.main.js:561
(anonymous) @ workbench.web.main.js:561
invoke @ workbench.web.main.js:90
deliver @ workbench.web.main.js:90
fire @ workbench.web.main.js:90
acceptChunk @ workbench.web.main.js:561
(anonymous) @ workbench.web.main.js:561
(anonymous) @ workbench.web.main.js:652
invoke @ workbench.web.main.js:90
deliver @ workbench.web.main.js:90
fire @ workbench.web.main.js:90
i.onload @ workbench.web.main.js:652
workbench.web.main.js:756 Can not restart the workspace from the local devfile: Error: Request failed with status code 500
```

**Comment by RomanNikitenko** [comment] 2023-06-01 08:41
> Maybee you can add some trace on testing image to get the answere retuned by server (full payload more than only the return code) ?

On the Che-Code side we use a library to generate new Devfile context. 
It's not easy process to add logs for that part if the cause of the problem on the lib side...

Anyway I've added additional logs on the Che-Code side: https://github.com/che-incubator/che-code/pull/236/commits/0d930e1a7035c4b9df232cb0728f28ccf15b26e1
So, please try it again when you have a chance...

**Comment by disaster37** [comment] 2023-06-01 11:43
console log:
```
[Extension Host] === Restart From Local Devfile === Starting to update Devfile process...
workbench.web.main.js:94 [Extension Host] === Restart From Local Devfile === DevfileService was created successfully!
workbench.web.main.js:94 [Extension Host] === Restart From Local Devfile === DevWorkspaceGenerator was created successfully!
workbench.web.main.js:94 [Extension Host] === Restart From Local Devfile === devfile path: /projects/web-nodejs-sample/devfile.yaml
workbench.web.main.js:94 [Extension Host] === Restart From Local Devfile === request for the current devfile was successful!
workbench.web.main.js:94 [Extension Host] === Restart From Local Devfile === using devfile /projects/web-nodejs-sample/devfile.yaml to generate a new Devfile context...
workbench.web.main.js:94 [Extension Host] === Restart From Local Devfile === using plugin registry URL https://che.rancher-hpd.hm.dm.ad/plugin-registry/v3 to generate a new Devfile context...
workbench.web.main.js:621   ERR [Extension Host] Something went wrong for the 'Restart From Local Devfile' action: Error: unable to verify the first certificate
workbench.web.main.js:94 [Extension Host] Something went wrong for the 'Restart From Local Devfile' action: Error: unable to verify the first certificate
y @ workbench.web.main.js:94
$logExtensionHostMessage @ workbench.web.main.js:1555
N @ workbench.web.main.js:1555
M @ workbench.web.main.js:1555
H @ workbench.web.main.js:1555
G @ workbench.web.main.js:1555
(anonymous) @ workbench.web.main.js:1555
invoke @ workbench.web.main.js:90
deliver @ workbench.web.main.js:90
fire @ workbench.web.main.js:90
fire @ workbench.web.main.js:561
E @ workbench.web.main.js:561
(anonymous) @ workbench.web.main.js:561
invoke @ workbench.web.main.js:90
deliver @ workbench.web.main.js:90
fire @ workbench.web.main.js:90
acceptChunk @ workbench.web.main.js:561
(anonymous) @ workbench.web.main.js:561
(anonymous) @ workbench.web.main.js:652
invoke @ workbench.web.main.js:90
deliver @ workbench.web.main.js:90
fire @ workbench.web.main.js:90
i.onload @ workbench.web.main.js:652
workbench.web.main.js:756 Can not restart the workspace from the local devfile: Error: unable to verify the first certificate
```

**Comment by disaster37** [comment] 2023-06-01 14:02
I my case, I get
```
[Extension Host] === Restart From Local Devfile === getCertificateAuthority for the path /public-certs
workbench.web.main.js:94 [Extension Host] === Restart From Local Devfile === getCertificateAuthority === CHE_SELF_SIGNED_MOUNT_PATH undefined
workbench.web.main.js:94 [Extension Host] === Restart From Local Devfile === getCertificateAuthority === the path /public-certs exists!
workbench.web.main.js:94 [Extension Host] === Restart From Local Devfile === getCertificateAuthority === found 2
```

**Comment by RomanNikitenko** [comment] 2023-06-06 08:02
I asked different people who faces the problem to test the current potential fix. 
I have got a positive feedback - the solution works for them.
But some of them still have the problem, like in the comment above. 

@disaster37 
As far as I understand the cause of the problem ^ is:
- `DevWorkspaceGenerator` lib does request to the plugin registry to get editor's devfile.yaml 
- according to the logs there are two certificates, at least the first one is not suitable
- the request fails =>  `DevWorkspaceGenerator` can not generate a new Devfile context

Yesterday I applied another approach within https://github.com/che-incubator/che-code/pull/236. It should allow to avoid requests to the plugin registry for the new Devfile context generation.

@disaster37 could you please test my changes again - I committed it to the same PR - so you can use the same image with editor, the same test-repo.
thanks in advance!

**Comment by disaster37** [comment] 2023-06-06 09:01
It  works. I have tested to modify the local devfile (the command name). After it reload workspace, I get the new command line.

On debug console, I look some error during process, but I haven't the time to get them

**Closed as completed** 2023-06-13 18:02 UTC
Labels: kind/bug, severity/P1, area/editor/vscode
