### ISSUE TITLE
Since 7.38.x, can't connect on workspace. 502 Bad Gateway 

### ISSUE THREAD

**Issue by disaster37** [eclipse/che#20781] opened 2021-11-16 14:19 UTC
### Describe the bug

When I launch new or existing workspace, I get error `502 Bad Gateway`. The workspace pod is successfully running and green badge is displayed on the workspace name.

It seems to have problem with URL and keykloak. It failed on request (return code 502):
```
https://che-test.rancher-hpd.hm.dm.ad/auth/realms/che/protocol/openid-connect/auth?client_id=che-public&redirect_uri=https%3A%2F%2Fche-test.rancher-hpd.hm.dm.ad%2F_app%2Floader.html%3FredirectUrl%3Dhttps%3A%2F%2Fche-test.rancher-hpd.hm.dm.ad%2Fserver03gf2m93-jwtproxy%2Fserver-4402%2F%26workspaceId%3Dworkspacegdtysto4k1xg016y&state=acbab698-5108-42a5-a7c1-86b8a7e05bb5&response_mode=fragment&response_type=code&scope=openid&nonce=1f30bc23-31f1-427c-ba51-e2f18a0822b1
```

I can successfully access on `https://che-test.rancher-hpd.hm.dm.ad/auth/realms/che/protocol/openid-connect/auth`, so it seems there are some problem on redirect...

### Che version

7.38@latest

### Steps to reproduce

1.Deploy Eclipse che from chectl with the following options:
```
chectl server:deploy --installer=operator --domain=che-test.rancher-hpd.hm.dm.ad --multiuser --chenamespace=che-test --cheboottimeout=600000 --platform=k8s --che-operator-cr-patch-yaml=che-operator-cr-patch.yaml --postgres-pvc-storage-class-name=nfs-client --workspace-pvc-storage-class-name=nfs-client --skip-kubernetes-health-check
```

The contend of che-operator-cr-patch.yaml:
```yaml
spec:
  k8s:
    singleHostExposureType: 'gateway'
    tlsSecretName: 'che-tls-certificates'
  metrics:
    enable: true
  server:
    serverExposureStrategy: 'single-host'
    proxyPort: "8080"
    proxyURL: 'http://squid.squid.svc.cluster.local'
    nonProxyHosts: 'localhost|10.0.0.0/8|.hm.dm.ad|.rancher-hpd.hm.dm.ad|.svc.cluster.local'
    useInternalClusterSVCNames: true
    workspaceNamespaceDefault: 'che-<username>'
    customCheProperties:
      CHE_LIMITS_USER_WORKSPACES_COUNT: "-1"
      CHE_LIMITS_USER_WORKSPACES_RUN_COUNT: "3"
      CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT: "43200000"
      CHE_INFRA_KUBERNETES_NAMESPACE_ANNOTATIONS: 'che.eclipse.org/username=<username>,field.cattle.io/projectId=c-57d7n:p-8j45h'
      CHE_INFRA_KUBERNETES_NAMESPACE_LABELS: 'app.kubernetes.io/part-of=che.eclipse.org,app.kubernetes.io/component=workspaces-namespace,field.cattle.io/projectId=p-8j45h'
      CHE_WORKSPACE_DEFAULT__CPU__LIMIT__CORES: '1'
      CHE_WORKSPACE_DEFAULT__CPU__REQUEST__CORES: '500m'
      CHE_WORKSPACE_SIDECAR_DEFAULT__CPU__LIMIT__CORES: '300m'
      CHE_WORKSPACE_SIDECAR_DEFAULT__CPU__REQUEST__CORES: '50m'
  storage:
    pvcClaimSize: 4Gi
    pvcStrategy: per-workspace
```

2. Run bash workspace
3. You get message `502 Bad Gateway` instead to access on theia UI.

### Expected behavior

Access on Theia UI

### Runtime

Kubernetes (vanilla), other (please specify in additional context)

### Installation method

chectl/latest

### Environment

Linux

### Eclipse Che Logs

```shell
There are no error logs from workspace, che server or keykloack pods.
```

### Additional context

Kubernetes is deployed with Rancher 2.6.2

**Comment by nils-mosbach** [comment] 2021-11-16 18:19
We had the same issue on rancher provisioned clusters due to default buffer limits of the ingress controller.

If you look at the ingress controller logs, there should pop up something like this:
```
upstream sent too big header while reading response header from upstream
```

Solution in our case was to increase `proxy-buffer-size` to `16k`. I think default is 8k which is exceeded by some (but not all) headers passed by keycloak.

---
*Project* `system` > *Namespace* `ingress-nginx` > *ConfigMap* `nginx-configuration`

![image](https://user-images.githubusercontent.com/15126675/142041816-f59186b9-a4ee-423f-84ab-730dca278508.png)

---
In our case that setting seems to get lost from time to time. Might be caused by Rancher updating ingress configurations.

**Comment by RomanNikitenko** [comment] 2021-11-17 07:09
@nils-mosbach 
thank you very much for sharing your experience about the problem!

@disaster37 
could you check if the suggestion above resolves problem on your side.

**Comment by disaster37** [comment] 2021-11-17 08:35
Hi, I have tested the workaround and it's work like a charm. Thx @nils-mosbach 
But I prefer to use annotation to custom only che ingress instead all nginx setting, aka `nginx.ingress.kubernetes.io/proxy-buffer-size: 16k`.

Maybee it make sense to add this annotation on default ingress annotation instead to overwrite and maintain `CHE_INFRA_KUBERNETES_INGRESS_ANNOTATIONS__JSON` ?

**Comment by skabashnyuk** [comment] 2022-02-04 09:16
Closing since https://github.com/eclipse-che/che-operator/pull/1200 merged.

**Closed as completed by skabashnyuk** 2022-02-04 09:16 UTC
Labels: kind/question
