### ISSUE TITLE
Can not start a workspace using Go sample

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse/che#23213] opened 2024-10-29 12:01 UTC
### Describe the bug

I get `Error creating DevWorkspace deployment: Detected unrecoverable event FailedPostStartHook: PostStartHook failed.` error when I start a workspace using `Go` sample.

### Che version

7.93@latest

### Steps to reproduce

Start a workspace for `Go` sample.

### Expected behavior

The workspace started successfully.

### Environment

I faced the problem on the dogfooding instance.

### Additional context

<img width="946" alt="image" src="https://github.com/user-attachments/assets/0194b346-a182-4582-8fe8-94ae9288df19">

**Comment by vinokurig** [comment] 2024-10-31 07:59
Could not reproduce on latest dogfooding instance, @RomanNikitenko can we close it?

**Comment by RomanNikitenko** [comment] 2024-10-31 08:04
Tested it again:

<img width="891" alt="image" src="https://github.com/user-attachments/assets/9e58ead0-284c-4cc8-9085-5a8ecb65d0c1">

**Comment by AObuchow** [comment] 2024-10-31 17:33
From my understanding, you need an SSH key with a passphrase configured for this bug to occur.

**Closed as completed** 2024-11-12 08:08 UTC
Labels: kind/bug, severity/P1, area/getting-started, area/devworkspace-operator
