### ISSUE TITLE
"Error: Loading CSS chunk 469 failed." in Dashboard after OCP auth session is expired

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse/che#22230] opened 2023-05-23 14:31 UTC
### Describe the bug

Dashboard of Eclipse Che Next has shown error "Loading CSS chunk 469 failed." after OCP auth session is expired:
```
Error: Loading CSS chunk 469 failed. (https://eclipse-che.apps.ocp410.crw-qe.com/dashboard/469.dfe56f9999e93c8993d4.css)

    in Unknown
    in t
    in t
    in RoutesComponent
    in Suspense
    in kt
    in main
    in div
    in Page
    in Dt
    in Connect(Dt)
    in t
    in c
    in i
    in Connect(i)
    in AppComponent
    in u
```

### Che version

next (development version)

### Steps to reproduce

1. Deploy Eclipse Che Next (7.68.0-SNAPSHOT) to OCP.
2. Go to Eclipse Che Dashboard.
3. Switch to another browser tab till auth session is expired.
4. Return to browser tab with Eclipse Che Dashboard and go to Workspaces page.

### Expected behavior

Workspaces page is opened

### Runtime

OpenShift

### Screenshots

![Screenshot from 2023-05-23 16-27-02](https://github.com/eclipse/che/assets/1197777/366c8c4e-396e-4103-bb85-4b39da0f3f82)

### Installation method

chectl/next

### Environment

Linux

### Additional context

There is workaround: refresh the browser page with Eclipse Che Dashboard.

**Comment by dkwon17** [comment] 2023-10-25 19:16
I have a few solutions:

<details><summary>In dashboard's ErrorBoundary, check the error code for the failed chunk request and direct the user to the login page if necessary.</summary>

Unfortunately there doesn't seem to be a way to check the reason (e.g. 403 or 404 error) why a `ChunkLoadError` occurred. Webpack populates [these fields](https://github.com/webpack/webpack/blob/87660921808566ef3b8796f8df61bd79fc026108/lib/css/CssLoadingRuntimeModule.js#L439C14-L442) in the error object (`error.type` is the same in both 403 and 404 cases). Also, response codes for requests are not available in `window.performance.getEntries()`.

Therefore to determine the error reason, `fetch` is used to make a request to the chunk once more. If the error code is 403, direct the user to the login page.  

Branch: https://github.com/dkwon17/che-dashboard/tree/1-fetch

[1-fetch.webm](https://github.com/eclipse/che/assets/83611742/e73ffb8b-ec81-4e42-8e3b-18ec08aed4f2)

</details>

<details><summary>In dashboard's ErrorBoundary, let testBackends() direct the user to the login page</summary>

For this solution, when the `Loading CSS chunk` error appears, call [this.props.onError()](https://github.com/eclipse-che/che-dashboard/blob/07e4e42bb4f8f72128e6470999931eb4ca5aee28/packages/dashboard-frontend/src/Layout/ErrorBoundary/index.tsx#L80C18-L80C25) which calls [testBackends()](https://github.com/eclipse-che/che-dashboard/blob/07e4e42bb4f8f72128e6470999931eb4ca5aee28/packages/dashboard-frontend/src/store/SanityCheck/index.ts#L77) 

The testBackends() function will eventually call [signIn()](https://github.com/eclipse-che/che-dashboard/blob/07e4e42bb4f8f72128e6470999931eb4ca5aee28/packages/dashboard-frontend/src/store/SanityCheck/index.ts#L118) since the `provision` requests will fail with 403.

For this solution, it takes a few seconds before the login page appears, because of the `provision` request retries.

Branch: https://github.com/dkwon17/che-dashboard/tree/2-check

[second-check.webm](https://github.com/eclipse/che/assets/83611742/ab8ad411-1944-4bba-bd4a-78a1fab1b5ff)

</details>


<details><summary>Skip authentication for `dashboard/*.css` and `dashboard/*.js` requests</summary>

For this solution, the `dashboard/*.css` and `dashboard/*.js` requests would skip auth checks in the oauth-proxy side.

https://github.com/eclipse-che/che-operator/blob/7997df38dc8ab7a79a554d1dd4de7024f831a82c/pkg/deploy/gateway/oauth_proxy.go#L147-L150

However this might not be safe to expose.

[third-skip.webm](https://github.com/eclipse/che/assets/83611742/565f7902-f248-4d93-8b4e-69c4f05c1125)

</details>


WDYT @dmytro-ndp @olexii4 @akurinnoy @ibuziuk ?

**Comment by akurinnoy** [comment] 2023-10-26 13:08
@dkwon17 I have two more options:

- get rid of lazy loading;
- use lazy loading with prefetch ([npmjs](https://www.npmjs.com/package/react-lazy-with-preload)).

The advantage of these options is that users will not see errors about loading chanks failures any more.

**Comment by dkwon17** [comment] 2023-10-27 17:27
Thanks for the feedback @akurinnoy , I have made a PR here: https://github.com/eclipse-che/che-dashboard/pull/965

**Comment by ibuziuk** [comment] 2023-10-31 09:21
Merged in main and the fix will be part of 7.77 / DS 3.10

**Comment by ibuziuk** [comment] 2024-03-21 10:50
@akurinnoy @olexii4 @dkwon17 reopening since I was able to reproduce a similar issue on Developer Sandbox:
<img width="1349" alt="Screenshot 2024-03-21 at 11 49 01" src="https://github.com/eclipse/che/assets/1461122/441d195b-15e1-4f60-bf88-7d62a61bef97">

**Comment by olexii4** [comment] 2024-09-17 15:09
Cannot reproduce with Eclipse Che Next 7.92.0-next. 
Please, reopen this PR if this bug will reproduce again.

**Closed as completed by olexii4** 2024-09-17 15:09 UTC
Labels: kind/bug, sprint/next, severity/P1, area/dashboard, team/A
