### ISSUE TITLE
It is not possible to restore operator to a different PostgreSQL version

### ISSUE THREAD

**Issue by tolusha** [eclipse/che#20812] opened 2021-11-23 09:18 UTC
### Describe the bug

It is not possible to restore operator to a different PostgreSQL version

### Che version

next (development version)

### Steps to reproduce

1. `chectl server:deploy --platform minikube --version 7.36.2`
2. `chectl server:update --version 7.38.2`
3. `chectl server:restore --rollback`

PostgreSQL pod failed to start
```
Incompatible data directory. This container image provides
PostgreSQL '9.6', but data directory is of
version '13'.
This image supports automatic data directory upgrade from
'9.5', please _carefully_ consult image documentation
about how to use the '$POSTGRESQL_UPGRADE' startup option.
```

### Expected behavior

Eclipse Che is successfully restored

### Runtime

minikube

### Installation method

chectl/next

### Environment

Linux

**Comment by mmorhun** [comment] 2021-12-07 11:50
In short: closing as won't fix.
The problem is that to deliver a fix for this issue we need to re-release all previous affected version of Che operator which is not the case.
However, the root cause of the problem - database format - has been fixed. Starting from the next release such problem should not appear in the future.

**Closed as completed by mmorhun** 2021-12-07 11:50 UTC
Labels: kind/bug, severity/P1, area/che-operator
