### ISSUE TITLE
Error building che-theia (error:0308010C:digital envelope routines::unsupported)

### ISSUE THREAD

**Issue by ghost** [eclipse/che#21567] opened 2022-07-20 06:04 UTC
### Summary

I am having mysterious build errors building che-theia (which I am trying to do in order to investigate if I can add plugins that way, see #21566). The problem occurs during the `yarn install` step (I have tried either running build.sh or just running yarn directly, same result). I will attach logs.

### Relevant information

[stdout.txt](https://github.com/eclipse/che/files/9146916/stdout.txt)
[stderr.txt](https://github.com/eclipse/che/files/9146918/stderr.txt)

OS: Fedora 36 in QEMU
npm: 8.3.1
node: 16.14.0
che-theia repository version: main branch (commit 2975fe868e9589bbd353d878de2fb34d36a013b4)

**Comment by yujiri8** [comment] 2022-07-20 17:06
Well, skipping the tests did suppress that error. I'm now getting an error about unsupported digital envelope routines. This is an error I previous saw with some other JS projects, and managed to fix by downgrading to node 14, but this time either version of node gives the same error. This is unlikely to have anything to do with che, but I'll paste it anyway
[stderr.txt](https://github.com/eclipse/che/files/9152218/stderr.txt)
.

**Comment by yujiri8** [comment] 2022-07-20 17:07
Oops, uploaded the wrong file. Here are the real ones
[stdout.txt](https://github.com/eclipse/che/files/9152238/stdout.txt)
[stderr.txt](https://github.com/eclipse/che/files/9152239/stderr.txt)

**Comment by azatsarynnyy** [comment] 2022-07-26 20:20
It seems this is some Webpack issue.
@yujiri8 
Can you try the following workaround: `export NODE_OPTIONS=--openssl-legacy-provider`
See https://github.com/webpack/webpack/issues/14532#issuecomment-947012063

**Comment by yujiri8** [comment] 2022-07-26 22:10
Oh yeah, I found that thread and tried that option, but the result is that node immediately exits with `/usr/bin/node: --openssl-legacy-provider is not allowed in NODE_OPTIONS`

**Comment by yujiri8** [comment] 2022-08-14 08:59
I have pulled the latest changes and still cannot build it with the same issue.

**Comment by azatsarynnyy** [comment] 2022-08-17 15:53
Hello @yujiri8 
I can't reproduce the mentioned problem by building it locally. The build is green on the CI https://github.com/eclipse-che/che-theia/actions/workflows/next-build.yml as well.

I'm thinking if that problem can be platform-specific... Some time ago, I had [a problem related to `digital envelope routines`](https://github.com/eclipse-theia/theia/issues/8378). It turned out it was reproducible on a machine with FIPS enabled.

**Comment by yujiri8** [comment] 2022-08-18 00:48
I suspect it's fedora specific, because I remember reading some other discussion about this error message where a solution was proposed but it didn't seem to work for people on fedora. I suppose this should be closed as it's unlikely that this issue is really che's fault.

**Closed as completed by yujiri8** 2022-08-18 00:48 UTC
Labels: kind/question, area/editor/theia, area/editors
