### ISSUE TITLE
If re-branded che-code won't connect to the embedded openvsx

### ISSUE THREAD

**Issue by jsomsanith** [eclipse/che#21962] opened 2023-01-27 18:51 UTC
### Summary

Hi Eclipse Che team 👋
(I don't know if that's a bug or something I missed in my configuration)

**What am I trying to do ?**
I want to run a vscode that consumes a custom che-plugin-registry for vscode extensions, instead of the default open-vsx.

**What have I done ?**
1. Build a che-plugin-registry with my extra extension in it.

2. Deploy Che on kubernetes, overriding the plugin registry image and setting `openVSXURL` to an empty string. (This is supposed to force the extension url to use the one from the embedded plugin-registry)

```yaml
kind: CheCluster
apiVersion: org.eclipse.che/v2
spec:
  components:
    pluginRegistry:
      openVSXURL: ""
      deployment:
        containers:
        - image: jsomsanith/che-plugin-registry:7.59.0
          imagePullPolicy: Always
```

**What result I have ?**
I create a new workspace in che, and in vs-code, while searching for extensions, it still consumes open-vsx and it doesn't find my extra extension.

### Relevant information

**What have I discovered during investigation ?**

1. The default extension url (open-vsx) is set in the [product.json](https://github.com/che-incubator/che-code/blob/main/code/product.json#L95) file in vscode.

2. On vscode build, a [script](https://github.com/che-incubator/che-code/blob/main/code/build/gulpfile.vscode.web.js#L100) replaces a placeholder in [product.ts](https://github.com/che-incubator/che-code/blob/d774fdfb748e0276c330fa478c80609fcef11b11/code/src/vs/platform/product/common/product.ts#L56) code. This code is the class that is injected everywhere to get the `product.json` configuration. It takes the content of `globalThis._VSCODE_PRODUCT_JSON` if defined, otherwise, it's the default content (that replaced the placeholder).

3. The che customisation of vscode introduces a script: [entrypoint-volume.sh](https://github.com/che-incubator/che-code/blob/main/build/scripts/entrypoint-volume.sh#L50). This script is executed on [workspace creation](https://github.com/eclipse-che/che-plugin-registry/blob/main/che-editors.yaml#L370).
If the `OPENVSX_REGISTRY_URL` env var is defined and is empty, it replaces the extensions url in product.json with the value of `CHE_PLUGIN_REGISTRY_URL` env var.

4. In my workspace devfile, I can see the correct values of the env vars
```yaml
components:
  - attributes:
      controller.devfile.io/merge-contribution: true
    container:
      env:
        - name: CHE_DASHBOARD_URL
          value: 'https://che.localtest.me'
        - name: CHE_PLUGIN_REGISTRY_URL
          value: 'https://che.localtest.me/plugin-registry/v3'
        - name: CHE_PLUGIN_REGISTRY_INTERNAL_URL
          value: 'http://plugin-registry.eclipse-che.svc:8080/v3'
        - name: OPENVSX_REGISTRY_URL
          value: ''
      image: 'quay.io/devfile/universal-developer-image:ubi8-0e189d9'
      memoryLimit: 512Mi
      mountSources: true
      sourceMapping: /projects
    name: tools
```

5. I checked the `product.json` in the pod and it contains the right replaced values (no open-vsx) 🎉.
**But**, in the che-code output, there is no web client code that will import and consume this `product.json`; only imported by some code that is executed on the (node) server side. 🤔
The scripts that the web vscode downloads, consumes the values from `product.ts`. `globalThis._VSCODE_PRODUCT_JSON` is not defined, so I end up with the default extension url.

**Comment by l0rd** [comment] 2023-01-30 23:37
@jsomsanith thank you for this detailed description of your issue. Have you tried in an incognito window? @azatsarynnyy does that rings a bell?

**Comment by jsomsanith** [comment] 2023-01-31 12:32
@l0rd I just tried in incognito mode, and I still have the query to open-vsx url when I search for extensions

**Comment by azatsarynnyy** [comment] 2023-01-31 14:02
From the issue description, it looks like everything is configured correctly, according to [the docs](https://www.eclipse.org/che/docs/stable/administration-guide/extensions-for-microsoft-visual-studio-code-open-source/).    
That's the way of configuring the plugin registry for an air-gapped environment. I haven't seen any related issues reported last time.
@svor could you take a look at it from the plugin registry side perspective, if nothing is missing in the described steps?

**Comment by nickboldt** [comment] 2023-01-31 14:23
Might be worth comparing the [downstream forked codebase](https://github.com/redhat-developer/devspaces-images/tree/devspaces-3-rhel-8/devspaces-pluginregistry) to see if we have anything that fixes this downstream which was never ported upstream for airgap or alternate registry support. 

But if the bug is in the che-code codebase, not the registry or operator... then that won't help as we're using more or less identical content in Che and DS for the vscode container.

**Comment by nickboldt** [comment] 2023-01-31 14:25
@azatsarynnyy does the che-code pod cache any details about which openvsx instance to use, that would need to be refreshed after the new registry pod is started? That is, would taking down the pod and creating a fresh one allow it to re-read the CheCluster info, or see the new registry URL?

**Comment by azatsarynnyy** [comment] 2023-01-31 14:42
> does the che-code pod cache any details about which openvsx instance to use

it reads it from the env. variable on each start

**Comment by svor** [comment] 2023-02-01 13:29
> From the issue description, it looks like everything is configured correctly, according to [the docs](https://www.eclipse.org/che/docs/stable/administration-guide/extensions-for-microsoft-visual-studio-code-open-source/). That's the way of configuring the plugin registry for an air-gapped environment. I haven't seen any related issues reported last time. @svor could you take a look at it from the plugin registry side perspective, if nothing is missing in the described steps?

It seems everything is correct in the procedure. I've deployed Che on OS with the patch to use local OpenVSX:
![screenshot-nimbusweb me-2023 02 01-15_22_21](https://user-images.githubusercontent.com/1271546/216055830-6f672745-6f87-4988-b816-f78796e540c9.png)
And in the extensions view I see only extensions from the custom registry:
![screenshot-nimbusweb me-2023 02 01-15_20_43](https://user-images.githubusercontent.com/1271546/216056021-fe91fc5e-345c-4798-be6c-8b6212dc15e7.png)

@jsomsanith could you please share the content of the CheCluster custom resource to check if the path was applied.

**Comment by jsomsanith** [comment] 2023-02-01 16:59
😮 that's promising. Must be a problem somewhere in my config.
Here is my CheCluster config 

```yaml
apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  creationTimestamp: "2023-01-27T09:59:29Z"
  finalizers:
  - checluster.che.eclipse.org
  - cheGateway.clusterpermissions.finalizers.che.eclipse.org
  - cheWorkspaces.clusterpermissions.finalizers.che.eclipse.org
  - namespaces-editor.permissions.finalizers.che.eclipse.org
  - devWorkspace.permissions.finalizers.che.eclipse.org
  - dashboard.clusterpermissions.finalizers.che.eclipse.org
  generation: 1
  name: eclipse-che
  namespace: eclipse-che
  resourceVersion: "395441"
  uid: 73faf54b-eea5-4d76-8085-3efd2229c157
spec:
  components:
    cheServer:
      debug: false
      logLevel: INFO
    dashboard:
      deployment:
        containers:
        - image: asaintsever/che-dashboard:7.59.0
          imagePullPolicy: Always
          name: che-dashboard
    database:
      credentialsSecretName: postgres-credentials
      externalDb: false
      postgresDb: dbche
      postgresHostName: postgres
      postgresPort: "5432"
      pvc:
        claimSize: 1Gi
    devWorkspace: {}
    devfileRegistry:
      deployment:
        containers:
        - image: asaintsever/che-devfile-registry:7.59.0
          imagePullPolicy: Always
          name: devfile-registry
    imagePuller:
      enable: false
      spec: {}
    metrics:
      enable: true
    pluginRegistry:
      deployment:
        containers:
        - image: jsomsanith/che-plugin-registry:7.59.0
          imagePullPolicy: Always
      openVSXURL: ""
  containerRegistry: {}
  devEnvironments:
    defaultComponents:
    - container:
        image: quay.io/devfile/universal-developer-image:ubi8-38da5c2
        sourceMapping: /projects
      name: universal-developer-image
    defaultEditor: che-incubator/che-code/insiders
    defaultNamespace:
      autoProvision: true
      template: <username>-che
    disableContainerBuildCapabilities: true
    secondsOfInactivityBeforeIdling: 1800
    secondsOfRunBeforeIdling: -1
    startTimeoutSeconds: 300
    storage:
      pvcStrategy: per-user
  gitServices: {}
  networking:
    auth:
      gateway:
        configLabels:
          app: che
          component: che-gateway-config
      identityProviderURL: http://dex.dex:5556
      oAuthClientName: eclipse-che
      oAuthSecret: EclipseChe
    domain: che.localtest.me
    tlsSecretName: che-tls
status:
  chePhase: Active
  cheURL: https://che.localtest.me
  cheVersion: 7.59.0
  devfileRegistryURL: https://che.localtest.me/devfile-registry
  gatewayPhase: Established
  pluginRegistryURL: https://che.localtest.me/plugin-registry/v3
  postgresVersion: "13.3"
  workspaceBaseDomain: che.localtest.me

```

**Comment by jsomsanith** [comment] 2023-02-01 18:26
Ok I found the issue !
We use the branding script in che-code to customize our vscode. This scripts merges the default `product.json` with the one in `branding/product.json`. The `extensionsGallery` part is the last in the json file in the default file, but not anymore with the merge.
A little after, in the process, a version will be inserted. So by default we have `extensionsGallery` followed by `version`, but after the branding merge, not anymore.

In the [entrypoint-volume.sh](https://github.com/che-incubator/che-code/blob/main/build/scripts/entrypoint-volume.sh#L66) we replace the extension endpoint in the `workbench.main.js` file (this is the line I missed 🤦‍♂️). But the regex used for the replacement doesn't match anything anymore because it tries to match `extensionsGallery` followed by `version`.

**Comment by svor** [comment] 2023-02-02 11:40
@jsomsanith do I understand correctly that you figured it out how to use the embedded OpenVSX registry? If yes, can we close the issue?

**Comment by jsomsanith** [comment] 2023-02-02 16:09
Yes I understood but in fact there is real issue.
If you customize the che-code image adding your branding, depending on what you add as branding configuration, you can end up with the same issue.

**Comment by l0rd** [comment] 2023-02-02 16:58
I have changed the title of the issue and labels to reflect new findings. What surprising is that we do customize che-code when building OpenShift Dev Spaces but we haven't faced this issue.

**Comment by jsomsanith** [comment] 2023-02-02 18:10
That depends on your branding/product.json content.
We have extra properties that are not in the original product.json, at the same level as extensionGallery. That adds them up after and break the replacement regex

**Comment by azatsarynnyy** [comment] 2023-02-07 12:50
@jsomsanith as it depends on the `branding/product.json` content, could you share a file content that can be used for reproducing the problem on our side?

Here's [the `branding/product.json` content](https://github.com/redhat-developer/devspaces-images/blob/devspaces-3-rhel-8/devspaces-code/branding/product.json) that we use for OpenShift Dev Spaces.

**Comment by jsomsanith** [comment] 2023-03-06 09:29
Hi @azatsarynnyy,
Sorry for the delay, the past weeks were intense for me.
Your `product.json` should introduce the issue 🤔. I have a similar one (same structure).

In [entrypoint-volume.sh](https://github.com/che-incubator/che-code/blob/main/build/scripts/entrypoint-volume.sh#L66) it tries the replace the `serviceUrl` and `itemUrl` from `extensionsGallery` block that must be followed by a `version` property (regex `serviceUrl:\".*\",itemUrl:\".*\"},version`).

When I run the `branding.sh` script, it adds a bunch of properties in `product.json`, that come from the `branding/product.json`. The `extensionsGallery` property is not the last one in the json structure anymore.

In the compiled code it doesn't fit the regex anymore (`version` doesn't follow `extensionsGallery`). On top of that I had to the `resourceUrlTemplate` property in `extensionsGallery` so this change breaks the regex too.
![image](https://user-images.githubusercontent.com/2874505/223070165-49e71fe5-0846-48e5-a125-5dbc8b459490.png)

**Comment by RomanNikitenko** [comment] 2023-05-03 08:49
Probably should fix https://github.com/che-incubator/che-code/pull/219.
I haven't tested it yet...

**Closed as completed** 2023-05-09 10:20 UTC
Labels: kind/bug, severity/P2, area/editor/vscode
