### ISSUE TITLE
GitHub authentication fails in VS Code if there is no PAT or if PAT has expired

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22080] opened 2023-03-21 18:05 UTC
### Describe the bug

This error is presented to the user when VS Code tries to authenticate the user to GH:

`Error: Invalid character in header content ["Authorization"]`

### Che version

next (development version)

### Steps to reproduce

2 ways to reproduce it:

**Cloning a repository from GitHub**
- Start an empty workspace
- Open the command palette and select the command `Git: Clone`
- Click "Clone from GitHub"

**Using the GitHub Pull Request Plugin**
- Start a workspace from a workspace (for example https://github.com/l0rd/dockerfile-hello-world)
- Install the `GH Pull Request and Issues` VS Code extension
- Click on the GitHub logo in the left sidebar and then `Sign in`

### Expected behavior

The user can sign in to GitHub and VS Code can use the GitHub API.

### Runtime

OpenShift

### Screenshots

![image](https://user-images.githubusercontent.com/606959/226701189-f94963ee-41e5-4cb3-bf1f-4e3bfa010bb7.png)

![image](https://user-images.githubusercontent.com/606959/226699096-d6249e6b-8622-41d5-8bd0-2be9a9f783f2.png)

### Installation method

OperatorHub

### Environment

Amazon

**Comment by RomanNikitenko** [comment] 2023-03-24 16:18
@l0rd 
I tried both ways for Chrome and Firefox, but I was not able to reproduce it on the dogfooding instance...
Maybe I should clean up something in my settings or other actions...


https://user-images.githubusercontent.com/5676062/227582594-5a2ddd97-01e4-4929-aabc-952e34c5582a.mp4

**Comment by l0rd** [comment] 2023-04-02 21:12
@RomanNikitenko here is another video that I have just recorded on the dogfooding instance. Let me know what I can provide you to help you reproduce it:

https://user-images.githubusercontent.com/606959/229379176-4897cf6f-a06b-457c-9879-393b1bbf8387.mp4

**Comment by l0rd** [comment] 2023-04-06 11:17
I have changed the title because I suspect that the problem is reproducible only when there is no GitHub personal access token is not present or has expired. 

In this video I show that if the github.com PAT is revoked then the GitHub authentication in VS Code fails:

![2023-04-06 12 32 44](https://user-images.githubusercontent.com/606959/230361540-f59ea6f3-af0a-4f50-8a20-eca54409d0fe.gif)

Hopefully this should help to reproduce the problem systematically.

**Comment by RomanNikitenko** [comment] 2023-04-06 13:17
I have another message:

<img width="647" alt="image" src="https://user-images.githubusercontent.com/5676062/230389864-29921d4b-318a-487d-99a4-0c93bd7a32c0.png">

but anyway, thank you, Mario, for detailed instructions for reproducing it!

**Comment by shakerg** [comment] 2023-04-15 18:53
Is this resolved by setting up the [GitHub OAuth App](https://www.eclipse.org/che/docs/stable/administration-guide/configuring-oauth-2-for-github/) (GitHub Apps) vs messing around with the personal access token?

**Comment by l0rd** [comment] 2023-04-16 20:28
I think that it could be reproduced with GitHub OAuth App too when the token is expired.

**Comment by shakerg** [comment] 2023-04-16 20:41
Unlike PAT's, [GitHub Apps & OAuth Apps ](https://docs.github.com/en/apps/creating-github-apps/creating-github-apps/differences-between-github-apps-and-oauth-apps)remain active until they are revoked. Here is more about creating an [OAuth App](https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/creating-an-oauth-app).

**Comment by l0rd** [comment] 2023-04-16 20:47
> Unlike PAT's, [GitHub Apps & OAuth Apps ](https://docs.github.com/en/apps/creating-github-apps/creating-github-apps/differences-between-github-apps-and-oauth-apps)remain active until they are revoked. Here is more about creating an [OAuth App](https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/creating-an-oauth-app).

Thank you for sharing the links. The Che OAuth App is used to create a PAT, if the user grants it, and that PAT expires. We do create a new PAT when it expires but I am afraid that something doesn't work as expected.

**Comment by rludva** [comment] 2023-05-22 10:50
Do we have any updates on this issue? 
It will be good to have this feature in EclipseChe/DevSpaces available.

I built a new image for the _Che Plugin Registry_ that contains the newest release of _GitHub.copilot-1.86.82.vsix_ in _quay.io/rludva/pluginregistry-rhel8:v1:09_ to test if the behavior is still the same. 

```
$ oc edit checlusters.org.eclipse.che devspaces -n openshift-devspaces
    pluginRegistry:
      deployment:
        containers:
          - image: quay.io/rludva/pluginregistry-rhel8:v1:09
        openVSXURL: ''
```
Looks like there is the same error message when it tryies to connect:

```
[INFO] [auth] [2023-05-22T10:48:45.369Z] Invalid copilot token: missing token: 404 
[ERROR] [default] [2023-05-22T10:48:45.371Z] GitHub Copilot could not connect to server. Extension activation failed: "User not authorized"
[INFO] [auth] [2023-05-22T10:48:46.136Z] Invalid copilot token: missing token: 404 
```

**Comment by RomanNikitenko** [comment] 2023-05-22 13:20
I see the current issue as a bug:
- let's say administrator configured the GitHub OAuth application according to [the docs](https://www.eclipse.org/che/docs/stable/administration-guide/configuring-oauth-2-for-github/) 
- user starts workspace using git url
- dahsboard redirects user to Github authorization page for the registered OAuth app
- user confirms authorization

As a result, the user has a token that is used for commands like "Clone from Github".

But let's say the token is expired or revoked - then the user encounters an unauthorized error. At this step the system could redirect user to the Github authorization page for the registered OAuth app to confirm authorization.

So, as far as I understand the current issue is not about configuring GitHub OAuth App from scratch. The application should be configured by admin according to [the docs](https://www.eclipse.org/che/docs/stable/administration-guide/configuring-oauth-2-for-github/).

**Comment by RomanNikitenko** [comment] 2023-05-22 13:34
About the GitHub Copilot extension - I tested and can confirm that the problem is not resolved even when GitHub OAuth application is configured, so unfortunately, resolving the current issue doesn't assume resolving GitHub Copilot activation problem.

**Comment by l0rd** [comment] 2023-05-23 15:07
We discussed briefly with @RomanNikitenko and we have decided to display an informative message to the user with the root cause of the problem and the instructions to fix it rather than implement the automatic update (that would probably require some work che-server side):

**If the token has expired and is managed by Che**

```
The GitHub token included in the workspace file '<token-path>' has expired. 
Restarting the workspace will automatically update the file with a new GitHub token.
```

**If the token has expired but is NOT managed by Che**

```
The GitHub token included in the workspace file '<token-path>' has expired. 
The expired token is stored in the secret <secret-name> and needs to be updated with a new one.
```

**If the token is not present and the workspace is managed by Che**

```
A valid GitHub token stored in file '<token-path>' is required for this feature to work.
Please reference to this [Eclipse Che documentation article](https://www.eclipse.org/che/docs/stable/end-user-guide/using-a-git-provider-access-token/) to learn how to automatically include one in your workspaces.
```
 
**If the token is not present and the workspace is NOT managed by Che**

```
A valid GitHub token stored in file '<token-path>' is required for this feature to work.
Please reference to this [DevWorkspace Operator documentation article](https://github.com/devfile/devworkspace-operator/blob/main/docs/additional-configuration.adoc#adding-git-credentials-to-a-workspace) to learn how to create a secret to automatically include one in your workspaces.
```

**Comment by RomanNikitenko** [comment] 2023-05-29 14:35
![image](https://github.com/eclipse/che/assets/5676062/c452841d-815b-4c67-b5c1-d4f2a015c477)

I'm testing some changes and have found that restarting a workspace is not helpful for that ^ use case if:
- a workspace is started from a sample, so - a `zip` (not `git`) project is used for starting workspace
or 
- an empty workspace is started

For such use cases dashboard doesn't redirect to the github authorization page at starting a workspace. I propose to handle it similar to the 3-rd use case with the reference to the documentation (see previous comment from Mario).

**Comment by RomanNikitenko** [comment] 2023-05-29 16:27
@l0rd 
what's the true way to check if a workspace is managed by Che? 
in the context of the current issue there is no problem to do it when the token is expired - it's enough just to check for the `app.kubernetes.io/part-of: che.eclipse.org` label of the corresponding secret.

But for the use cases when the token is not present - could you clarify - what's the way to check if a workspace is managed by Che?

**Comment by tolusha** [comment] 2023-05-30 08:35
I think it is about checking the field `spec.devEnvironments.defaultNamespace.autoProvision` in the CheCluster CR.
if it is `true`, then workspace is managed by Che

https://github.com/eclipse-che/che-operator/blob/47d5ae3f05aadf8b622779673d50f07e8d33e4a0/api/v2/checluster_types.go#L377

**Comment by RomanNikitenko** [comment] 2023-05-31 07:54
@tolusha 
thank you for the answer, at the moment I'm blocked by another problem: 

I've added `"@kubernetes/client-node": "^0.16.1"` dependency to the `che-github-authentication` extension and have got dependencies problem:

<img width="1189" alt="image" src="https://github.com/eclipse/che/assets/5676062/08d04cb9-da7c-4997-975a-915270232d16">

so will try your suggestion after resolving ^...

**Closed as completed** 2023-06-26 09:23 UTC
Labels: kind/bug, severity/P1, area/editor/vscode
