### ISSUE TITLE
It is pot possible to install node packages globally (EACCES: permission denied, mkdir '/usr/local/lib/node_modules')

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse/che#22955] opened 2024-05-07 10:19 UTC
### Describe the bug

I am not able to install node package globally because of permission denied (see the screenshot).
It is reproducible on both dogfooding and sandbox instances.

### Steps to reproduce

1. Create any node-based workspace
2. Open a terminal and install the package
```
npm install -g vsce
```

### Expected behavior

The package must be installed.

### Runtime

OpenShift

### Screenshots

![Screenshot from 2024-05-07 13-10-01](https://github.com/eclipse-che/che/assets/1655894/8bc8792f-4437-4405-939a-d738a3a82fa4)

### Installation method

other (please specify in additional context)

### Environment

Dev Sandbox (workspaces.openshift.com)

**Comment by AObuchow** [comment] 2024-05-09 22:48
@vitaliy-guliy this seems to be a duplicate of https://github.com/eclipse-che/che/issues/21742

Is this issue a new priority? What is the use case -- for multi-project workspaces? This should be fixable by the suggestions left in https://github.com/eclipse-che/che/issues/21742, but we should decide whether we want the global node modules to persist or be ephemeral.

Let's perhaps close this issue in favour of https://github.com/eclipse-che/che/issues/21742 and continue the discussion there.

**Comment by ibuziuk** [comment] 2024-05-15 15:35
Closing in favour of https://github.com/eclipse-che/che/issues/21742

**Closed as completed by ibuziuk** 2024-05-15 15:35 UTC
Labels: kind/bug, severity/P1, team/B
