### ISSUE TITLE
Workspace template does not start from Dashboard UI

### ISSUE THREAD

**Issue by artaleks9** [eclipse/che#20532] opened 2021-09-24 07:28 UTC
### Describe the bug

A workspace template does not start from Dashboard UI

### Che version

next (development version)

### Steps to reproduce

1. Deploy CHE on minikube
```sh
cat EOF << > /tmp/patch.yaml
spec:
  server:
    cheImage: 'quay.io/eclipse/che-server'
    cheImageTag: 'nightly'
    customCheProperties:
      CHE_LIMITS_USER_WORKSPACES_RUN_COUNT: '-1'
      CHE_WORKSPACE_SIDECAR_IMAGE__PULL__POLICY: IfNotPresent
      CHE_WORKSPACE_PLUGIN__BROKER_PULL__POLICY: IfNotPresent
      CHE_INFRA_KUBERNETES_WORKSPACE_START_TIMEOUT_MIN: '12'
  auth:
    updateAdminPassword: false
EOF

chectl server:deploy --k8spodreadytimeout=600000 --k8spodwaittimeout=600000 --k8spoddownloadimagetimeout=600000 --listr-renderer=verbose --platform=minikube --che-operator-cr-patch-yaml=/tmp/patch.yaml --telemetry=off --chenamespace=eclipse-che

```
2. Go to Dashboard
3. Try to run a workspace from a template

### Expected behavior

* A workspace template should run

### Runtime

Kubernetes (vanilla)

### Screenshots

![che-no-start-ws](https://user-images.githubusercontent.com/5408906/134635173-ec6bf8ff-5773-43c1-8606-9288be31c498.png)

### Installation method

chectl/next

### Environment

Linux

**Comment by sleshchenko** [comment] 2021-09-24 07:51
It turned out that failure is caused by nightly which was built 3 months ago.
It should be fixed when e2e test used next Che Server image.

**Comment by dmytro-ndp** [comment] 2021-09-24 16:20
@sleshchenko: good catch!
Nightly Eclipse Che Happy path tests have been fixed to use "**che-server:next**".

**Closed as completed** 2021-09-24 16:21 UTC
Labels: kind/bug, severity/blocker, e2e-test/failure, area/qe
