### ISSUE TITLE
404 Error when opening the dashboard

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#22352] opened 2023-07-11 12:39 UTC
### Describe the bug

<img width="1023" alt="image" src="https://github.com/eclipse/che/assets/606959/8ff39b64-64ab-47b4-a7a2-1483f59d0df4">

From time to time I experience errors when connecting to the dashbaord. Both on sandbox and dogfooding clusters.

### Che version

next (development version)

### Steps to reproduce

Open the dashboard URL

### Expected behavior

No errors

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Amazon

**Comment by ibuziuk** [comment] 2023-07-18 15:28
similar issue that was caught during periodic tests 
[output.webm](https://github.com/eclipse/che/assets/1461122/e565147b-1850-4b74-b1d4-4ce76e947222)

**Comment by dkwon17** [comment] 2023-08-30 20:08
I was able to reproduce the `Failed to fetch plugins from registry URL: , reason: 404 page not found` error on Dev Spaces 3.7.2 on workspaces.openshift.com.

According to the error message, the problem seems to be because the dashboard thinks the plugin registry URL is an empty string:
https://github.com/eclipse-che/che-dashboard/blob/d3f9c09230cc861c8eb2fc3960e3339c62f756f2/packages/dashboard-frontend/src/store/Plugins/chePlugins/index.ts#L69

I'm not able to reproduce this issue on DS 3.8 or latest Che, it might be already fixed by https://github.com/eclipse-che/che-dashboard/commit/6a6caf375f5b403687459a18b0bf37eb4caf8fb0 because that PR changes how the plugin regsitry url is retrieved cc @olexii4

**Comment by l0rd** [comment] 2023-10-26 13:13
@svor @dkwon17 @tolusha is this one fixed? Can we close it?

**Comment by dkwon17** [comment] 2023-10-27 13:47
@l0rd we are planning to close this issue once we verify that the fixes work on DS 3.10 RC on the staging cluster (since the issue is more common on staging compared to dogfooding)

**Comment by ibuziuk** [comment] 2023-11-08 14:29
Closing after merging https://github.com/eclipse-che/che-dashboard/pull/980

**Closed as completed by ibuziuk** 2023-11-08 14:29 UTC
Labels: kind/bug, sprint/next, severity/P1, area/dashboard
