### ISSUE TITLE
After deleting a workspace the DevWorkspaceTemplate still exists

### ISSUE THREAD

**Issue by olexii4** [eclipse/che#21013] opened 2022-01-13 12:07 UTC
### Describe the bug

I created the workspace from a sample. After I deleted it, I couldn't create a new workspace from that sample anymore. 

### Che version

next (development version)

### Steps to reproduce

1. Click on a sample to create a workspace
2. Delete the workspace
3. Try to create a workspace from the previous sample

### Expected behavior

The new workspace's being created via factory flow.

### Runtime

minikube

### Screenshots

![Знімок екрана 2022-01-13 о 13 21 55](https://user-images.githubusercontent.com/6310786/149327441-13f62f6a-b188-4326-9ae4-a8570033755a.png)

### Installation method

chectl/next

### Environment

macOS

**Comment by nickboldt** [comment] 2022-01-13 13:16
Should this be reported in https://github.com/devfile/devworkspace-operator/issues ?

**Comment by ibuziuk** [comment] 2022-01-13 13:35
I think it should be addressed as part of https://github.com/devfile/devworkspace-operator/issues/692

**Comment by amisevsk** [comment] 2022-01-13 15:05
This looks like two issues, neither of which DWO is in control of:
1. DevWorkspaceTemplates are being created for DevWorkspaces with static names (e.g. `theia-ide-bash`). I think these are being created by the dashboard itself, as DWO does not create DWTs in a normal flow.
2. DevWorkspaceTemplates are being created without owner references

The first item above goes beyond this issue, as likely we'll run into a problem where we can't the same workspace twice in one namespace from factory (workspace 1 gets a DWT named `theia-ide-bash`, workspace 2 tries to create the same DWT and fails). The fix for this would be to either suffix DWTs so they're DevWorkspace-specific, or to deliberately reuse DWTs (check if `theia-ide-bash` DWT exists and is up to date rather than plain create)

The second item is the reason the DWT wasn't removed when the workspace is deleted. By design, references in DevWorkspaces to DevWorkspaceTemplates are meant to be reused (e.g. WTO uses two DWTs to define web terminal exec and tooling for the whole cluster). This means that DWO has no mechanism for removing DevWorkspaceTemplates used by DevWorkspaces. The solution to this would be to make sure any resources created for a specific DevWorkspace have an owner ref to that DevWorkspace.

To fix:
1. Che should either reuse DWTs (e.g. create/update `theia-ide-bash-<version>`) in a given namespace, or create unique DWTs for a DevWorkspace
2. Che should either set an ownerref on DWTs it creates, or figure out a way to delete them when it deletes a DevWorkspace.

**Closed as completed** 2022-01-21 15:31 UTC
Labels: kind/bug, severity/P1, area/dashboard
