### ISSUE TITLE
Error creating workspace with devfile for che-dashboard using git link

### ISSUE THREAD

**Issue by moonbse** [eclipse/che#22576] opened 2023-10-03 07:40 UTC
### Summary 

alert:Failed to create the workspace
Error occurred during creation a workspace from devfile located at `https://raw.githubusercontent.com/eclipse-che/che-dashboard/333d6cf1142994533f6eea7f0d7568e5e6f45245/devfile.yaml`. Cause: Could not reach devfile at `Connect timed out`

This has happened before too but it resolved on its own , not the case this time. Earlier I thought it is actually a connection timeout but I checked network, it all looks fine.

![Screenshot from 2023-10-03 12-00-32](https://github.com/eclipse/che/assets/29522373/c2114cbc-9443-40f4-8a9e-c9ce2f259494)

server is respoding with 400 , there is ssl issue too. 
I am using brave browser, also tried with firefox to same result
![Screenshot from 2023-10-03 13-08-12](https://github.com/eclipse/che/assets/29522373/6f4d9e93-edaf-4483-9943-88ad97a32375)

**Comment by ibuziuk** [comment] 2023-10-03 10:54
@vinokurig could you please take a look?

**Comment by ibuziuk** [comment] 2023-10-03 10:58
I can not reproduce the issue on workspaces.openshift.com
@moonbse which version of the Eclipse Che are you using?
<img width="1716" alt="Screenshot 2023-10-03 at 12 57 38" src="https://github.com/eclipse/che/assets/1461122/9266b299-e748-471b-b0ce-f205e9767601">

**Comment by moonbse** [comment] 2023-10-03 11:06
@ibuziuk I am using 

```
Dashboard Version
7.76.0-next
Server Version
7.76.0-SNAPSHOT
```

Right now I am able to open the workspace, it starts to happen sometime , I don't understand how but then after an hour I tried it worked. I also tried on openshift workspace, it worked there after few attempts.

**Comment by ibuziuk** [comment] 2023-10-05 07:59
>  I don't understand how but then after an hour I tried it worked. I also tried on openshift workspace, it worked there after few attempts. 

It seems to be some networking issue related to accessing https://raw.githubusercontent.com/eclipse-che/che-dashboard/333d6cf1142994533f6eea7f0d7568e5e6f45245/devfile.yaml

Closing for now, but feel free to reopen if you still have the problem. If you hit it please, try to execute curl against the URL and check that it is accessible.

**Closed as completed by ibuziuk** 2023-10-05 07:59 UTC
Labels: kind/bug, kind/question, status/analyzing, severity/P1, area/che-server
