### ISSUE TITLE
Cannot create a factory from repository (without devfile) that has uppercase characters in name

### ISSUE THREAD

**Issue by SkorikSergey** [eclipse/che#21338] opened 2022-04-19 12:34 UTC
### Describe the bug

Cannot create a factory from repository(without devfile) that has uppercase characters in name.
There are restrictions:
```Unable to create devworkspace: DevWorkspace.workspace.devfile.io "TestRepo" is invalid: metadata.name: Invalid value: "TestRepo": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')``` 

### Che version

other (please specify in additional context)

### Steps to reproduce

1. Try to create a factory from repository(without devfile) that has uppercase characters in name, for example from this - https://github.com/SkorikSergey/TestRepo.

### Expected behavior

Workspace created and started successfully.

Suggested behaviour change is that the factory / devworkspace engine will sanitize the input GH repo name to make it compliant with OCP naming rules.

### Runtime

OpenShift

### Screenshots

![Selection_005](https://user-images.githubusercontent.com/7760565/164003581-95c1a56d-eb70-408d-a88e-2f70d60fd54f.png)

### Installation method

OperatorHub

### Environment

Linux

### Additional context

Eclipse Che 7.47.0

**Comment by nickboldt** [comment] 2022-04-19 12:39
Suggested behaviour change is that the factory / devworkspace engine will sanitize the input GH repo name to make it compliant with OCP naming rules.

**Comment by artaleks9** [comment] 2022-04-19 13:48
Also this bug can be reproduced if customer devfile have ver. 1.0 and metadata with name in upper case, e.g.
```
apiVersion: 1.0.0
metadata:
  name: testName

```
In this case we'll get the same error.
After fix the problem should check also this test case.

**Comment by nickboldt** [comment] 2022-04-19 23:40
@SkorikSergey what happens with accented characters? Do we sanitize those already? Or break when French or Spanish or Arabic characters are used?

**Comment by SkorikSergey** [comment] 2022-04-20 07:49
@nickboldt It is not possible to create repo with Arabic characters. And also with characters like ä, ö, ü.

**Comment by ibuziuk** [comment] 2022-04-20 10:43
@l0rd wdyt should the fix be part of 3.0 ?

**Comment by l0rd** [comment] 2022-04-20 11:19
This is not a blocker because it's a corner case: there is no devfile, the repo name has uppercase letters. But if it's an easy fix and there is no risk to postpone the release let's include that.

**Comment by ibuziuk** [comment] 2022-05-25 13:09
Fixed in https://github.com/eclipse-che/che-dashboard/pull/527

**Closed as completed** 2022-05-25 13:09 UTC
Labels: kind/bug, severity/P1, area/factory/server, area/factory/dashboard
