### ISSUE TITLE
che-code - Open IDE redirects too fast: `Bad Gateway`

### ISSUE THREAD

**Issue by nils-mosbach** [eclipse/che#21099] opened 2022-01-31 15:51 UTC
### Describe the bug

If starting a new Workspace opening the IDE e.g. che-code is triggered to fast and responds with a `Bad Gateway`. If clicked refresh in the browser after 2 seconds everything loads as expected. Maybe che-code or the traeffik configration is not yet ready? 

So basically the redirect from here

![image](https://user-images.githubusercontent.com/15126675/151826064-10b31888-e2c6-491c-9204-17a5e9604dbf.png)

to the IDE happens to fast.

![image](https://user-images.githubusercontent.com/15126675/151825040-801886a5-3f5a-45ac-bb80-92ea1700cc7e.png)

Startup times of workspaces are incredibly fast after we switched to devworkspaces. Great improvement! :)

### Che version

next (development version)

### Steps to reproduce

Start che-code environment.

### Expected behavior

Che code should be opened as soon as its ready.

### Runtime

Kubernetes (vanilla)

### Installation method

chectl/latest

### Environment

Linux

**Comment by benoitf** [comment] 2022-01-31 16:19
might be an issue related to https://github.com/eclipse/che/issues/20481

I'm also facing the issue

**Comment by benoitf** [comment] 2022-02-01 13:16
issue is not inside the editor because after few time the route is working fine

it's related to route availability

**Comment by benoitf** [comment] 2022-02-01 16:02
@amisevsk @sparkoo how is the route flagged as ready ? it seems that route is flagged as ready before traefik is able to reach the endpoint ?

I get rid of the connectionToken parameter so CheCode endpoint should return either 200 or nothing if not yet started

For Red Hatters it can be reproduce with https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/#https://github.com/che-incubator/che-code

**Comment by amisevsk** [comment] 2022-02-01 20:47
On the DWO side, the DevWorkspace is not marked as "started" until `<mainUrl>/healthz` returns a 2xx (or 4xx) status code (4xx is assumed to mean "unimplemented").

Testing locally, I'm seeing that `curl <che-gateway>/<workspaceID>/dev/3100/healthz` returns 404 not found -- does Che Code serve this endpoint?

**Comment by l0rd** [comment] 2022-02-01 22:36
I also get that with Che Theia from time to time.

**Comment by benoitf** [comment] 2022-02-02 12:29
of course that che-code is serving this endpoint (hitting refresh few seconds later after the 'bad gateway' message just works fine)

**Comment by benoitf** [comment] 2022-02-02 12:31
it looks like healthz may say that che-code is ok to receive requests but traefik is not yet updated to handle that route then it fails
because error is coming from traefik

**Comment by amisevsk** [comment] 2022-02-02 14:42
> che-code is serving this endpoint (hitting refresh few seconds later after the 'bad gateway' message just works fine)

I don't think it's relevant in this case, but note that issues with `/healthz` are easily obscured since we have to accept 4xx status codes as successes. Testing it with che-code, I've seen `404` and `401` response codes even in up-and-running workspaces, so it does seem like something somewhere is going wrong.

**Comment by benoitf** [comment] 2022-02-02 14:52
401 response is gone in the latest builds (there was a mandatory token in previous builds) so 401 could happen before but not anymore (as token is not required)
And in Theia, Mario reproduced the issue and for sure there is no token/401 error

**Comment by benoitf** [comment] 2022-02-02 14:54
BTW it looks still odd while 404 can be accepted as a success b/c if theia or code is not launched, it will return a 404 during the initialiaation

it looks like some race condition: someone notify it's ready while the traefik route is not

**Comment by amisevsk** [comment] 2022-02-02 20:36
PR https://github.com/eclipse-che/che-operator/pull/1309 should resolve this issue (tested briefly, at least). Changes are available in image `quay.io/amisevsk/che-operator:issue-21099` (replaces `quay.io/eclipse/che-operator:next`)

However, on the topic of `/healthz` endpoints, from what I can tell both Theia and che-code return 404 status codes:

Theia:
```shell
bash-5.0$ curl http://localhost:3100/healthz -I
HTTP/1.1 404 Not Found
```

Che-code:
```shell
bash-4.4$ curl http://localhost:3100/healthz -i 
HTTP/1.1 404 Not Found
Content-Type: text/plain
Date: Wed, 02 Feb 2022 20:33:22 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Transfer-Encoding: chunked

Not found.
```

c.f. Web terminal, for example:
```shell
bash-4.4 ~ $ curl -k https://localhost:4444/healthz -i
HTTP/2 200 
content-length: 0
date: Wed, 02 Feb 2022 20:33:02 GMT
```

**Comment by benoitf** [comment] 2022-02-02 20:40
But healthz is not managed by theia or code. There is no such endpoint

**Comment by amisevsk** [comment] 2022-02-02 20:50
> But healthz is not managed by theia or code. There is no such endpoint

Ah, sorry -- I was confused. It seemed like you were saying that Theia/Che-code were serving `/healthz` [here](https://github.com/eclipse/che/issues/21099#issuecomment-1027894136). If this is the case, and we stop treating 404 as success (as in https://github.com/eclipse/che/issues/21099#issuecomment-1028021105) then DevWorkspaces with Theia and Che-code will never enter a running state.

A more proper solution for readiness/liveness checks would be https://github.com/devfile/api/issues/168

**Comment by benoitf** [comment] 2022-02-02 20:52
But for exemple why is it not checking the path of the main endpoint ?

Like / instead of /healthz ?

**Comment by benoitf** [comment] 2022-02-02 20:53
HEAD request on the main endpoint / for both theia and vscode

**Comment by amisevsk** [comment] 2022-02-02 21:03
The history of the decision is found in https://github.com/eclipse-che/che-machine-exec/pull/105 and https://github.com/devfile/devworkspace-operator/pull/78. In a general sense, checking `/` on the main endpoint is not exactly reliable either, and `/healthz` is/was more-or-less a Kubernetes standard. 

Ironically, doing a HEAD request on `/` would result in precisely the bug reported here, since it would redirect to oauth as in https://github.com/eclipse/che/issues/20481:

```
curl -IL https://che-<snip>/workspaced642721e6fb04d37/dev/3100/
HTTP/1.1 302 Found
<snip>

HTTP/1.1 200 OK
<snip>
```

In fact, the reason this bug happened is because excluding `/healthz` from auth was failing for some workspaces (see the description to https://github.com/eclipse-che/che-operator/pull/1309 for an explanation).

**Comment by benoitf** [comment] 2022-02-02 21:11
well the gateway component is intercepting the calls so it could intercept handle the /healthz and check if the underlying service is returning 200 or not

Why put a gateway in every container if it doesn't bring value


It looks like strange to patch theia and vscode server to add a /healthz entrypoint

**Closed as completed** 2022-02-03 08:49 UTC
Labels: kind/bug, severity/P1, area/che-operator, area/gateway
