### ISSUE TITLE
DWO gets unexpected 404 response code for the health check request

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse/che#22163] opened 2023-04-18 10:45 UTC
### Describe the bug

I implemented health check endpoint for Che-Code within https://github.com/eclipse/che/issues/22008:
- DWO makes the request for `healthz`
- Che-Code returns `503` response code while the server is not available
- `200` response code is returned when server is ready to serve requests

In general it works as expected, but from time to time DWO makes the request and does get a `404` instead of `503`. It leads to the bug:
- workspace status is changed like: `Starting` => `Running` => `Starting`
- dashboard tries to open IDE and a user sees `404` page

It looks like the cause of the problem is on the traefik side: https://github.com/traefik/traefik/issues/7347.
We need to workaround it somehow.
Probably we could:
- consider that the endpoint is unimplemented (`404`) only if DWO has got `404` response code 3 times in a row
or
- implement health check endpoint for the IDEA and change a workspace status only when DWO has got `200` response (do not change the status on the `404` response code) 
or
- see https://github.com/eclipse/che/issues/22008#issuecomment-1513400912
or
- please share your ideas

### Che version

7.63@latest

### Steps to reproduce

See https://github.com/eclipse/che/issues/22008

### Expected behavior

- workspace status should be changed only when server on the Che-Code side is available to serve requests (ideally - when DWO has got `200` response code for the `healthz` request)
- `404` page should not be displayed for a user at a workspace startup

### Additional context

I'm able to reproduce the problem on the cluster provided by the Cluster Bot, see `Steps to Reproduce` section in https://github.com/eclipse/che/issues/22008

**Comment by RomanNikitenko** [comment] 2023-04-18 20:04
Please see an idea from @amisevsk https://github.com/eclipse/che/issues/22008#issuecomment-1513400912

**Comment by dkwon17** [comment] 2023-04-25 21:06
I have a band-aid fix idea on the traefik side, however it does not solve the root problem with 404: https://github.com/eclipse-che/che-operator/pull/1670. With this fix, there is a risk of an infinite loop if the IDE endpoint always returns 404 for whatever reason, although this shouldn't happen

**Comment by RomanNikitenko** [comment] 2023-04-27 06:42
It looks like the issue has become more urgent:
- I was able to reproduce the problem very seldom when I created the issue
- now - I face the problem every start of a workspace
- more over - it requires refreshing a page few times to get my IDE working

If anyone can confirm the same behaviour (`it requires refreshing a page few times to get my IDE working`) - I would consider this issue as a blocker - because for a user it looks like the IDE is not available when it's required to refresh the page 3-4 times.

Recently we have added some additional logic to the entrypoint - maybe now it requires more time to start VS Code and it  exacerbates the problem...

**Comment by l0rd** [comment] 2023-04-28 08:06
This has become systematic for me too on dogfooding. I have raise to `severity/blocker`. 

> maybe now it requires more time to start VS Code and it exacerbates the problem...

@RomanNikitenko if this is confirmed we should rollback the changes. Slowing down workspaces start is a regression. Plus this issue that has become systematic.

**Comment by dmytro-ndp** [comment] 2023-05-01 14:39
The issue has been reproduced in Dev Spaces 3.6.0.RC-04-27 + DWO 0.20.0.RC : https://issues.redhat.com/browse/CRW-4337

**Comment by RomanNikitenko** [comment] 2023-05-03 09:48
> This has become systematic for me too on dogfooding. I have raise to `severity/blocker`.
> 
> > maybe now it requires more time to start VS Code and it exacerbates the problem...
> 
> @RomanNikitenko if this is confirmed we should rollback the changes. Slowing down workspaces start is a regression. Plus this issue that has become systematic.

I thought that the regression was caused by recently merged changes to the `Che-Code`. 
I didn't find such regression on the `Che-Code` side within my investigation. Moreover, I see the same behaviour (I have to refresh a page few times) when I start a workspace with `che-code:7.62.0` version of editor. So, I believe the regression is not on the `Che-Code` side.

**Comment by RomanNikitenko** [comment] 2023-05-03 12:30
In addition to my previous comment - from my logs it looks like there is a quite long delay between the server is ready and a first request, so `server is ready to serve requests` ==> `delay` ==> `first request`

![delay_requests](https://user-images.githubusercontent.com/5676062/235916141-c5d6cfd6-6e54-4f47-bc10-10e9d69522cf.png)

**Comment by RomanNikitenko** [comment] 2023-05-04 13:47
I've found that the regression came from the `che-operator` side.

Starting a workspace with `che-operator:7.65.0`:


https://user-images.githubusercontent.com/5676062/236224255-16192178-e01c-4536-892d-da5abb8b6184.mp4

Starting a workspace for the same project with `che-operator:next`:


https://user-images.githubusercontent.com/5676062/236224745-4ab4bc27-f2b4-41ad-b9da-524e5e2a72ae.mp4

**Comment by amisevsk** [comment] 2023-05-04 15:22
Taking a glance at the Che Operator itself, there doesn't seem to be anything that could cause this regression. The PRs merged since 7.65 are

* https://github.com/eclipse-che/che-operator/pull/1663
* https://github.com/eclipse-che/che-operator/pull/1666
* https://github.com/eclipse-che/che-operator/pull/1669
* https://github.com/eclipse-che/che-operator/pull/1671
* https://github.com/eclipse-che/che-operator/pull/1639

Note however that the `next` version of the Che Operator will deploy the `next` versions of dashboard, che-gateway, and all other components, so the scope of what could have changed is larger.

**Comment by amisevsk** [comment] 2023-05-04 15:28
Looking at those PRs a second time, it appears that #1639 caused the default CPU limit for the gateway to be `25m` -- that sounds like a likely cause for networking issues :) 

This one's my bad -- I missed this in review.

**Closed as completed** 2023-05-05 08:41 UTC
Labels: kind/bug, severity/blocker, area/devworkspace-operator, team/B

**Comment by l0rd** [comment] 2023-05-05 10:36
> The issue has been reproduced in Dev Spaces 3.6.0.RC-04-27 + DWO 0.20.0.RC : [issues.redhat.com/browse/CRW-4337](https://issues.redhat.com/browse/CRW-4337)

@dmytro-ndp can you confirm that this problem happened sporadically, not systematically, with 3.6.0.RC? I am asking because the exacerbation of this issue was related to [this PR](https://github.com/eclipse-che/che-operator/pull/1639) that should not be in 3.6.

**Comment by dmytro-ndp** [comment] 2023-05-08 00:53
@l0rd : yes, I can confirm, that in Dev Spaces 3.6.0 the issue is reproduced not always, but sporadically.
