### ISSUE TITLE
Restart from Local Devfile fails if the devfile specifies which container to inject the IDE into

### ISSUE THREAD

**Issue by cgruver** [eclipse/che#23045] opened 2024-07-18 15:10 UTC
### Describe the bug

If a devfile specifies the attribute, `controller.devfile.io/merge-contribution: true` on a component, then `restart from local devfile` will fail if a user tries to modify the devfile in any way.

### Che version

7.88@latest

### Steps to reproduce

Create a workspace from [https://github.com/cgruver/dev-spaces-issue-reproducer.git](https://github.com/cgruver/dev-spaces-issue-reproducer.git)

With no modifications to the devfile, attempt to restart from local devfile

Choose the devfile in the `/issue-reproducer` folder (The one that the workspace was created with)

Observe the failure: `Failed to update Devfile. HttpError: HTTP request failed`

### Expected behavior

Workspace should restart

### Runtime

OpenShift

### Screenshots

<img width="500" alt="Screenshot 2024-07-18 at 11 09 38 AM" src="https://github.com/user-attachments/assets/7568ba4b-8eea-4868-b52f-a8b6f442bd81">

### Installation method

OperatorHub

### Environment

macOS

**Comment by AObuchow** [comment] 2024-07-18 15:27
This is either being caused by the restart from local devfile feature or an issue with devworkspace container contributions. Since the workspace is starting up correctly the first time, but failing after restart from local devfile, I suspect it has to do with an edge case in the restart from local devfile feature.

**Comment by vitaliy-guliy** [comment] 2024-07-22 10:20
I was able to easily restart the workspace following steps to reproduce.
Tested on Che 7.90.0-SNAPSHOT, Dashboard 7.89.0-next and che-code 1.92.0 (taken from Help->About)

@cgruver could you specify Che, dashboard and che-code versions as well?

**Comment by cgruver** [comment] 2024-07-22 11:30
OpenShift Dev Spaces 3.15 - Eclipse Che 7.88
Dashboard - 7.88.1 `registry.redhat.io/devspaces/dashboard-rhel8@sha256:59d743ce17724b3d4490eaa7e157cdcad33577adea6995e94a16fffb4112ff52`
che-code:

```
Version: 1.92.0
Commit: Unknown
Date: 2024-07-16T16:26:25.663Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15
```

**Comment by cgruver** [comment] 2024-07-22 11:31
This may already be fixed upstream.

**Comment by vitaliy-guliy** [comment] 2024-07-22 13:57
> This may already be fixed upstream.

It could be so.
In my PR che-incubator/che-code#390 I improved handling the errors while restarting the workspace from local devfile. It will allow to better understand the reasons of failures when parsing/applying the devfile.

**Comment by vitaliy-guliy** [comment] 2024-07-29 13:52
@cgruver I will close this issue as non relevant.
Feel free to reopen it if necessary.

**Closed as completed by vitaliy-guliy** 2024-07-29 13:52 UTC
Labels: kind/bug, severity/P1, area/editor/vscode
