### ISSUE TITLE
Starting a Che sample fails because "projects" is not found

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#21114] opened 2022-02-03 11:49 UTC
### Describe the bug

I have tried to start the Python sample and the Go sample. In both cases I get the following error:

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/606959/152337131-ad621dc3-847f-4bb2-add4-3fdb95f4c11e.png">

### Che version

next (development version)

### Steps to reproduce

Click on the sample

### Runtime

The team dogfooding instnace

**Comment by amisevsk** [comment] 2022-02-03 16:06
Oddly, I'm able to reproduce it fairly consistently with the Go sample, but not the Python one. I'm looking into it.

**Comment by ibuziuk** [comment] 2022-02-07 10:26
I still have this problem with ` spec.template.spec.initContainers[0].volumeMounts[0].name: Not found: "projects"` against `python-hello-world` getting started

**Comment by l0rd** [comment] 2022-02-07 10:32
I have it against any getting started

**Comment by ibuziuk** [comment] 2022-02-07 10:38
setting the blocker priority for 7.44

**Comment by amisevsk** [comment] 2022-02-07 14:55
I looked into this a bit last week but it seems to be inconsistent (perhaps the cluster and its load/size are involved?). I can't reproduce it in testing environments, nor when I try to attach debugging.

**Comment by amisevsk** [comment] 2022-02-07 20:33
Figured this one out after some live-debugging in the dogfooding cluster:

* The Dashboard initially creates empty DevWorkspaces with just the project defined (https://github.com/eclipse/che/issues/21138) -- not an issue per se but causes this issue to manifest
* The Dashboard then immediately updates this DevWorkspace with components/the default editor/etc.
* However, if the Dashboard takes too long to update the DevWorkspace, https://github.com/devfile/devworkspace-operator/issues/772 is triggered and DevWorkspace startup fails.

This issue is fixed by https://github.com/devfile/devworkspace-operator/pull/773

**Comment by ibuziuk** [comment] 2022-02-08 14:03
@amisevsk thanks for the investigation but still can reproduce it with python devfiles against dogfooding :man_shrugging:

**Comment by amisevsk** [comment] 2022-02-08 14:24
@ibuziuk the dogfooding cluster was still running DWO from commit [`b8cae02b`](https://github.com/devfile/devworkspace-operator/commit/b8cae02bebcd53bad555dcadfb6dc84d7db5f278), it looks like new images aren't being pulled automatically in the `next` index. Should be fixed now.

**Comment by amisevsk** [comment] 2022-02-08 18:17
PR https://github.com/devfile/devworkspace-operator/pull/774 should both ensure a new, up-to-date `next` image is pushed and also prevent this issue from happening going forward.

**Comment by ibuziuk** [comment] 2022-02-09 09:47
Thanks, works like a charm
Can not reproduce the issue against dogfooding anymore. Closing

**Closed as completed by ibuziuk** 2022-02-09 09:47 UTC
Labels: kind/bug, severity/blocker, sprint/current, area/dashboard, area/devworkspace-operator
