### ISSUE TITLE
Observations deploying current nightly version of Che

### ISSUE THREAD

**Issue by l0rd** [eclipse/che#20981] opened 2022-01-05 10:08 UTC
### Summary

I have installed Che next on OCP (cluster-bot) using `chectl server:deploy --platform=openshift`. Here are some observations.

### [Fixed] Eclipse Che operator description is outdated
Eclipse Che operator description says:

> This operator installs PostgreSQL, Keycloak, Plugin registry, Devfile registry and the Eclipse Che server, as well as configures all three services.”

Description needs to be reviewed.
<img width="887" alt="image" src="https://user-images.githubusercontent.com/606959/148196028-81801db8-e2ac-46df-8978-2c25e0695db2.png">

### [Fixed] There are still 2 operator channels
Using the "eclipse-che-preview" CatalogSource I can see 2 channels “next” and “next-all-namespaces”. Shouldn’t be one only?
<img width="759" alt="image" src="https://user-images.githubusercontent.com/606959/148196067-6ff0ea4a-3a32-4d2a-8c1c-3adcf3868100.png">

### [Dedicated issue] Backup/Restore API 
I can see the Backup/Restore API still there. If it doesn’t work with DevWorkspaces we should remove them.
<img width="1472" alt="image" src="https://user-images.githubusercontent.com/606959/148196210-2f911750-90dd-45d5-95e1-4805b7f67679.png">

### [Fixed] The version of the DevWorkspace operator installed
The installed version of the DevWorkspace is 0.10.0 (I was expecting next / 0.12.0)
<img width="516" alt="image" src="https://user-images.githubusercontent.com/606959/148196403-a285ff12-b420-4cae-a163-e637c2a3fea8.png">

### [Explained] Operands Pods
What’s “eclipse-che-preview” and the pod named “664dfaf464a4b88c439632189072fd9fd1fc3e2752141ea530151d--1-4pt5g” (spec.container.image is `quay.io/eclipse/eclipse-che-openshift-opm-bundles:7.42.0-401.next`)?
<img width="1478" alt="image" src="https://user-images.githubusercontent.com/606959/148197996-1c7f7027-c7b5-4b20-aa6d-6e5c15bdd24f.png">

### [Can't reproduce] Other issues I have noticed deploying Che from OperatorHub UI

I tried to deploy Che next without chectl, using the OperatorHub UI. I had to add to manually add the catalog source first:

```bash
kubectl apply -f - <<EOF
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: eclipse-che-preview
  namespace: openshift-operators
spec:
  sourceType: grpc
  image: quay.io/eclipse/eclipse-che-openshift-opm-catalog:next
  updateStrategy:
    registryPoll:
      interval: 5m
EOF
```

Deploying through the UI I noticed that

**Operands are deployed in openshift-operators namespace**

I have created CheCluster CR in namespace `eclipse-che` (default one) but che-gateway, registries, postgres, che-server, che-gateway, che-dashboard are deployed in `openshift-operators` namespace. That’s a lot of noise in this shared namespace.

**I am not able to access the dashboard (although route exist and the gateway logs are ok)**
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/606959/148199710-09fa2f78-54bb-434b-b670-23d59d2284c8.png">

**Comment by tolusha** [comment] 2022-01-05 12:22
**[FIXED] There are still 2 operator channels**

Fixed by rebuilding a catalog source without bundles related to `next-all-namespaces` channel.

**[CAN'T REPRODUCE] Other issues I have noticed deploying Che from OperatorHub UI**

1.  Create a custom catalog source

```bash
$ kubectl apply -f - <<EOF
> apiVersion: operators.coreos.com/v1alpha1
> kind: CatalogSource
> metadata:
>   name: eclipse-che-preview
>   namespace: openshift-operators
> spec:
>   sourceType: grpc
>   image: quay.io/eclipse/eclipse-che-openshift-opm-catalog:next
>   updateStrategy:
>     registryPoll:
>       interval: 5m
> EOF
catalogsource.operators.coreos.com/eclipse-che-preview created
```

2. Install Eclipse Che operator in `openshift-operators` namespace (from `next` channel)

![screenshot-console-openshift-console apps ci-ln-2gkhx7k-72292 origin-ci-int-gce dev rhcloud com-2022 01 05-13_54_53](https://user-images.githubusercontent.com/1640675/148213755-b21dfdd8-2ba6-4a40-8d53-efae32cfba1e.png)

3. Create `eclipse-che` namespace

```bash
$ oc create namespace eclipse-che
namespace/eclipse-che created
```

4. Create `CheCluster` custom resource in `eclipse-che` namespace

![sceenshort](https://user-images.githubusercontent.com/1640675/148215022-7af57f98-b169-4d2c-94d0-d38623a37e57.png)

5. Eclipse Che is deployed in `eclipse-che` namespace and accessable (fix is required: https://github.com/eclipse-che/che-operator/pull/1278)

![Untitled2](https://user-images.githubusercontent.com/1640675/148216464-82b4fb56-7685-46e6-a7a5-84e7a9561918.png)

**Comment by tolusha** [comment] 2022-01-11 10:37
**[FIXED] Eclipse Che operator description is outdated**

https://github.com/eclipse-che/che-operator/pull/1283

**Comment by tolusha** [comment] 2022-01-13 09:34
**[FIXED] The version of the DevWorkspace operator installed**

https://github.com/che-incubator/chectl/pull/1913

**Comment by tolusha** [comment] 2022-01-13 09:35
**Backup/Restore API**

Will be tracked separately https://github.com/eclipse/che/issues/21006

**Comment by tolusha** [comment] 2022-01-14 07:36
**[FIXED] The version of the DevWorkspace operator installed**

https://github.com/che-incubator/chectl/pull/1913

**Comment by tolusha** [comment] 2022-01-14 07:39
**[Explained] Operands Pods**

What’s “eclipse-che-preview” and the pod named “664dfaf464a4b88c439632189072fd9fd1fc3e2752141ea530151d--1-4pt5g” (spec.container.image is quay.io/eclipse/eclipse-che-openshift-opm-bundles:7.42.0-401.next)?

It is custom catalog source to deploy Eclipse Che from the `next` channel

**Closed as completed** 2022-01-14 07:40 UTC
Labels: kind/task, severity/P2, area/che-operator
