### ISSUE TITLE
chetctl deploy on K8S : PostgreSQL pod bootstrap : Starting failed

### ISSUE THREAD

**Issue by EnergieZ** [eclipse/che#21239] opened 2022-03-09 09:42 UTC
### Describe the bug

On a fresh kubernetes (managed by OVH, version 1.22.2-2), chectl failed to deploy. 
Keycloax is installed with succes and works fine.
OIDC is well configured as well.

```
PS C:\Users\xxxx> chectl server:deploy --domain=ide.dev.seven-group.com --platform=k8s --skip-oidc-provider-check
› Installer type is set to: 'operator'
› Current Kubernetes context: 'kubernetes-admin@INTERNE'
  √ Verify Kubernetes API...OK
  √ �  Looking for an already existing Eclipse Che instance
    √ Verify if Eclipse Che is deployed into namespace "eclipse-che"...it is not
  √ �  DevWorkspace engine
    √ Verify cert-manager installation
      √ Check Cert Manager deployment...already deployed
      √ Wait for Cert Manager...ready
  √ ✈️  Kubernetes preflight checklist
    √ Verify if kubectl is installed
    √ Verify remote kubernetes status...done.
    √ Check Kubernetes version: Found v1.22.2.
    √ Verify domain is set...set to ide.dev.seven-group.com.
    ↓ Check if cluster accessible [skipped]
  √ Following Eclipse Che logs
    √ Start following Operator logs...done
    √ Start following Eclipse Che Server logs...done
    √ Start following PostgreSQL logs...done
    √ Start following Keycloak logs...done
    √ Start following Plug-in Registry logs...done
    √ Start following Devfile Registry logs...done
    √ Start following Eclipse Che Dashboard logs...done
    √ Start following namespace events...done
  √ Create Namespace eclipse-che...[Exists]
  √ �‍  Running the Eclipse Che operator
    √ Create ServiceAccount che-operator in namespace eclipse-che...done.
    √ Read Roles and Bindings...done.
    √ Creating Roles and Bindings...done.
    √ Create CRD checlusters.org.eclipse.che...done.
    √ Waiting 5 seconds for the new Kubernetes resources to get flushed...done.
    √ Create deployment che-operator in namespace eclipse-che...done.
    √ Operator pod bootstrap
      √ Scheduling...done
      √ Downloading images...done
      √ Starting...done
    √ Prepare Eclipse Che cluster CR...Done.
    √ Create the Custom Resource of type checlusters.org.eclipse.che in the namespace eclipse-che...done.
  > ✅  Post installation checklist
    > PostgreSQL pod bootstrap
      √ Scheduling...done
      √ Downloading images...done
      × Starting...failed
        → Failed to start a pod, reason: Error, exitCode: 1
      Keycloak pod bootstrap
      Devfile Registry pod bootstrap
      Plug-in Registry pod bootstrap
      Eclipse Che Dashboard pod bootstrap
      Eclipse Che Server pod bootstrap
      Eclipse Che status check
    Retrieving Che self-signed CA certificate
    Prepare post installation output
    Error: Command server:deploy failed. Error log: C:\Users\xxxx\AppData\Local\chectl\error.log.
```

### Che version

7.44@latest

### Steps to reproduce

1. launch this command : `chectl server:deploy --domain=mydomain.com --platform=k8s --skip-oidc-provider-check` (skip-oidc-provider-check because of managed k8s, but oidc is ok)

### Expected behavior

Eclipse Che should install without any problem

### Runtime

other (please specify in additional context)

### Installation method

chectl/latest

### Environment

Windows

### Eclipse Che Logs

```shell
2022-03-09T09:28:56.797Z Error: Command server:deploy failed. Error log: C:/Users/jpillias/AppData/Local/chectl/error.log.
2022-03-09T09:28:56.797Z     at newError (C:/ProgramData/chectl/chectl/lib/util.js:199:19)
2022-03-09T09:28:56.797Z     at Object.wrapCommandError (C:/ProgramData/chectl/chectl/lib/util.js:195:12)
2022-03-09T09:28:56.797Z     at Deploy.<anonymous> (C:/ProgramData/chectl/chectl/lib/commands/server/deploy.js:189:35)
2022-03-09T09:28:56.797Z     at Generator.throw (<anonymous>)
2022-03-09T09:28:56.797Z     at rejected (C:/ProgramData/chectl/chectl/node_modules/tslib/tslib.js:115:69)
2022-03-09T09:28:56.797Z     at runMicrotasks (<anonymous>)
2022-03-09T09:28:56.797Z Cause: Error: Failed to start a pod, reason: Error, exitCode: 1
2022-03-09T09:28:56.797Z     at KubeTasks.<anonymous> (C:/ProgramData/chectl/chectl/lib/tasks/kube.js:134:35)
2022-03-09T09:28:56.797Z     at Generator.next (<anonymous>)
2022-03-09T09:28:56.797Z     at fulfilled (C:/ProgramData/chectl/chectl/node_modules/tslib/tslib.js:114:62)
2022-03-09T09:28:56.797Z     at runMicrotasks (<anonymous>)
```

### Additional context

I have try to change deployment of postgres in eclipse-che namespace : change readinessProbe timeoutSeconds to 30 and periodSeconds to 20

Still the same problem.

The postgres pod is always in "Back-off restarting failed container"

`kubectl logs postgres-xxxx-xxxx-n eclipse-che`result : 
```
mkdir: cannot create directory '/var/lib/pgsql/data/userdata': Permission denied
```

**Comment by EnergieZ** [comment] 2022-03-09 10:54
For information tried with stable and next channel of chectl : same problem

**Comment by l0rd** [comment] 2022-03-09 14:39
@EnergieZ thank you for your feedback. This looks like a duplicate of https://github.com/eclipse/che/issues/21095 and is related to Kubernetes clusters running on OVH. I am going to close this issue as duplicate but let's continue the discussion on [here](https://github.com/eclipse/che/issues/21095). Also don't hesitate to reach us through [Che mailing list](https://accounts.eclipse.org/mailing-list/che-dev) or joining [Che weekly community call](https://github.com/eclipse/che/wiki/Che-Dev-Meetings).

**Closed as completed by l0rd** 2022-03-09 14:39 UTC
Labels: kind/bug, status/duplicate

**Comment by Divine1** [comment] 2022-04-28 07:15
@l0rd  what is OVH?
