### ISSUE TITLE
Container build support doesn't work after upgrade from 7.58.0 to 7.59.0

### ISSUE THREAD

**Issue by cgruver** [eclipse/che#21927] opened 2023-01-09 15:53 UTC
### Describe the bug

Che version 7.59 seems to have broken rootless podman on OpenShift

OpenShift - OKD 4.12 SCOS

### Che version

7.59@latest

### Steps to reproduce

1. Install Che with `chectl server:deploy -p openshift`
1. Enable container builds:
   `oc patch CheCluster eclipse-che -n eclipse-che --type merge --patch '{"spec":{"devEnvironments":{"disableContainerBuildCapabilities":false}}}'`
1. Create a workspace with the empty project sample
1. Open a terminal in che-code
1. Execute `podman images`
1. Observe error:
   ```bash
   WARN[0000] "/" is not a shared mount, this could cause issues or missing mounts with rootless containers 
   ERRO[0000] running /usr/bin/newuidmap 289 0 1000700000 1 1 10000 65536: newuidmap: write to uid_map failed: Operation not permitted 
   Error: cannot set up namespace using "/usr/bin/newuidmap": exit status 1
   ```

### Expected behavior

Successful empty list of images

### Runtime

OpenShift

### Installation method

chectl/latest

### Environment

macOS

### Release Notes Text

A regression in the support for building containers has been fixed in this release.

**Comment by cgruver** [comment] 2023-01-09 16:07
Possible hint.  I updated to the Next channel and now I get an informative error on creating a workspace:

`Failed to start the workspace workspace-dev, reason: Failed to update workspace 'workspace-dev'. Unable to patch devworkspace: admission webhook "mutate.devworkspace-controller.svc" denied the request: user is not permitted use the container-build SCC`

**Comment by ibuziuk** [comment] 2023-01-09 16:37
@cgruver thank you for reporting the issue. 
Could you please clarify which version of Dev Workspace Operator is used on the cluster? Basically, with the latest 7.59.0 and DWO 0.18.0 podman builds should work fine

**Comment by cgruver** [comment] 2023-01-09 16:54
`devworkspace-operator.v0.18.1   DevWorkspace Operator   0.18.1            devworkspace-operator.v0.18.0   Succeeded`

**Comment by l0rd** [comment] 2023-01-09 17:09
I can reproduce that on our internal (dogfooding) instance. 

Looking at this issue I have found a few other problems:
1) the UDI tag used when starting an empty workspace is `ubi8-38da5c2` which is [6 months old](https://quay.io/repository/devfile/universal-developer-image?tab=tags) (!)
2) the empty workspace DevWorkspace includes VS Code metadata although those are already defined as contribution in the VS Code metadata

**Comment by cgruver** [comment] 2023-01-09 17:20
Let me know if you come up with a work around that I can apply to my cluster.  Or...  if it's possible to reinstall 7.58.

I downgraded chectl back to 7.58, but it still installs the latest from the stable channel in from Operator Hub.

**Comment by cgruver** [comment] 2023-01-09 18:25
Work around:

`chectl server:deploy --starting-csv=eclipse-che.v7.58.0 -p openshift`

This will force install v7.58.0 with a manual update strategy.

**Comment by amisevsk** [comment] 2023-01-09 22:01
I've reproduced this on OpenShift 4.11 and come out even more confused than before after testing.

Testing 7.58.0 vs 7.59.0, I've found

* In both versions, the workspace starts up, there is no issue 'using' the container-build scc. The same version of DWO is used behind the scenes in both versions when installing in a new cluster
* In both versions, the devworkspace, scc, and workspace pod are identical, with the only difference being a different image for the `che-code-injector` component and the addition of 
    ```yaml
        allowPrivilegeEscalation: false
        capabilities:
          add:
            - SETGID
            - SETUID
    ``` 
    to the pod security context
* After testing update from 7.58.0 to 7.59.0 twice, I saw
    * First time: `podman images` succeeds in 7.59.0 after updating
    * Second time: `podman images` fails as expected, but _old_ che-code-injector image is used (is registry not being updated?)

I haven't tested for Che `next`, but that error is even stranger. The error
> `Failed to start the workspace workspace-dev, reason: Failed to update workspace 'workspace-dev'. Unable to patch devworkspace: admission webhook "mutate.devworkspace-controller.svc" denied the request: user is not permitted use the container-build SCC`

is reported when the user does not have permissions to use the requested SCC, which is _not_ occuring in either 7.58.0 nor 7.59.0

**Comment by amisevsk** [comment] 2023-01-09 22:08
Testing a little further, it appears to be due to Che 7.59.0 adding
```yaml
  config:
    workspace:
      containerSecurityContext:
        allowPrivilegeEscalation: false
```
to the default Pod security context. 

Is there a reason we use `false` here? The SCC Che defines includes
```
allowPrivilegeEscalation: true
```

**Comment by amisevsk** [comment] 2023-01-09 22:11
PR https://github.com/eclipse-che/che-operator/pull/1576 sets `allowPrivilegeEscalation: false` in the DWOC.

**Comment by l0rd** [comment] 2023-01-09 22:18
We [should set it to `true`](https://github.com/eclipse/che/issues/21770#issuecomment-1290990178).

**Comment by cgruver** [comment] 2023-01-10 10:53
Very ugly workaround... that will at least let you work with containers in 7.59 for now:

```bash
oc patch dwoc devworkspace-config -n eclipse-che --type merge --patch '{"config":{"workspace":{"containerSecurityContext":{"allowPrivilegeEscalation":true}}}}'
```

You will have to rerun it immediately after creating a new workspace because the operator will revert it to false every time it touches the DWOC.

**Comment by cgruver** [comment] 2023-01-10 10:53
@l0rd @amisevsk Let me know when you have a new build on the Next channel.  I'll update one of my clusters to that version.

**Comment by amisevsk** [comment] 2023-01-10 16:11
@cgruver I've opened PR https://github.com/eclipse-che/che-operator/pull/1596; once merged should be pushed to the next channel fairly quickly (though I still haven't looked into the issue you encountered with the `next` channel, so there may be further issues). We should also backport this PR to the 7.59.x branch to fix the bug for all users.

**Closed as completed** 2023-01-11 15:39 UTC
Labels: kind/bug, status/analyzing, sprint/current, severity/P1, engine/devworkspace, new&noteworthy, new&noteworthy/che-only, status/release-notes-review-needed
