### ISSUE TITLE
[DevWorkspace] Workspace doesn't contain plugins if it's created with Custom Devfile flow

### ISSUE THREAD

**Issue by svor** [eclipse/che#20558] opened 2021-09-30 14:31 UTC
### Describe the bug

Workspace doesn't load plugins described in `.vscode/extensions.json` file if it was created from the devfile template.

### Che version

7.37@latest

### Steps to reproduce

1. Deploy Che with DevWorkspace
2. Go to the dashboard Create Workspace -> Custom Workspace
3. Select Java Spring Boot template and create a workspace
4. Workspace doesn't contain `redhat.java` plugin described in [extensions.json](https://github.com/che-samples/java-spring-petclinic/blob/devfilev2/.vscode/extensions.json) 

### Expected behavior

vscode-java plugin should be loaded

### Runtime

minikube

### Screenshots

![screenshot-192 168 49 2 nip io-2021 09 30-17_28_23](https://user-images.githubusercontent.com/1271546/135474596-93af92af-7401-4f2c-8c84-c5805e4004a8.png)

![screenshot-192 168 49 2 nip io-2021 09 30-17_29_00](https://user-images.githubusercontent.com/1271546/135474714-bdeb295a-cc53-49ff-beb7-b2db43afcae3.png)

![screenshot-192 168 49 2 nip io-2021 09 30-17_27_34](https://user-images.githubusercontent.com/1271546/135474464-4275946e-995c-4002-9b89-6d3a9b5fdc8c.png)

### Installation method

chectl/next

### Environment

Linux

**Comment by sleshchenko** [comment] 2021-10-01 15:07
That's expected behaviour, which we probably should better expose.

**Comment by akurinnoy** [comment] 2022-02-02 09:26
I'm closing this issue because the Custom Workspace tab is not available to users anymore.

**Closed as completed by akurinnoy** 2022-02-02 09:26 UTC
Labels: kind/bug, severity/P2, area/dashboard, engine/devworkspace
