### ISSUE TITLE
Failed to start a workspace: args is not defined

### ISSUE THREAD

**Issue by tolusha** [eclipse/che#22919] opened 2024-04-15 07:43 UTC
### Describe the bug

Failed to start a workspace from the dashboad

### Che version

next (development version)

### Steps to reproduce

1. Deploy Che on OpenShift
2. Create a workspace
3. Try to start a workspace by clicking `Action` - >`Open` button

### Expected behavior

Workspace is up and runinng

### Runtime

OpenShift

### Screenshots

![screenshot-eclipse-che apps ci-ln-89rblfk-76ef8 origin-ci-int-aws dev rhcloud com-2024 04 15-09_41_30](https://github.com/eclipse-che/che/assets/1640675/43c002c0-50bd-421d-b59a-b086e4bd327b)

### Installation method

chectl/next

### Environment

Linux

**Comment by ibuziuk** [comment] 2024-04-15 16:32
@akurinnoy is it really P2 or should we raise priority?

**Comment by akurinnoy** [comment] 2024-04-17 08:16
@tolusha I can't reproduce the issue using the steps in the description. Can you please confirm whether the problem still exists or not?

@ibuziuk that makes sense, thanks

**Comment by tolusha** [comment] 2024-04-17 09:04
![Screenshot from 2024-04-17 11-03-04](https://github.com/eclipse-che/che/assets/1640675/c7d8135b-efe7-43db-b051-ce1ba9d1dd25)
![Screenshot from 2024-04-17 11-02-27](https://github.com/eclipse-che/che/assets/1640675/e61e04ab-48d8-4de1-a5df-3cdcd82f87ba)

**Comment by akurinnoy** [comment] 2024-04-18 07:57
After some digging with @tolusha , we figured out that it was one of the Chrome extensions causing the problem. Disabling the extension fixed the issue.

I'm closing this issue because there's nothing we need to fix on the dashboard side.

**Closed as completed by akurinnoy** 2024-04-18 07:57 UTC
Labels: kind/bug, severity/P1, area/dashboard
