### ISSUE TITLE
workbench ui has meaningless menu option > chectl login

### ISSUE THREAD

**Issue by tsadigovAgmail** [eclipse/che#21418] opened 2022-05-21 15:41 UTC
### Describe the bug

This menu option is meaningless because the command does not exist in chectl

### Che version

next (development version)

### Steps to reproduce

open menu

### Expected behavior

not having this menu option

### Runtime

minikube

### Screenshots

![image](https://user-images.githubusercontent.com/1032344/169658936-2cf06aba-1069-450e-8f1d-070890337cfe.png)

### Installation method

chectl/next

### Environment

Linux

**Comment by l0rd** [comment] 2022-05-23 16:52
Hi @tsadigovAgmail thank you for your feedback. 

I am going to close this issue as it looks like a duplicate of https://github.com/eclipse/che/issues/21070. Feel free to re-open if that's not the case.

**Closed as completed by l0rd** 2022-05-23 16:52 UTC
Labels: kind/bug, status/need-triage
