### ISSUE TITLE
Plugin registry build is failed

### ISSUE THREAD

**Issue by svor** [eclipse/che#22954] opened 2024-05-07 08:49 UTC
### Describe the bug

The build of [che-plugin-registry ](https://github.com/eclipse-che/che-plugin-registry) is failed.
Error message is:
```
16.10 PostgreSQL 12 for RHEL / Rocky / AlmaLinux 8 -  567 kB/s | 1.2 MB     00:02    
16.95 Red Hat Universal Base Image 8 (RPMs) - BaseOS  2.0 MB/s | 719 kB     00:00    
17.57 Red Hat Universal Base Image 8 (RPMs) - AppStre 8.5 MB/s | 3.0 MB     00:00    
18.78 Red Hat Universal Base Image 8 (RPMs) - CodeRea 412 kB/s | 102 kB     00:00    
19.65 Error: 
19.65  Problem 1: conflicting requests
19.65   - nothing provides glibc = 2.28-236.el8_9.12 needed by glibc-minimal-langpack-2.28-236.el8_9.12.x86_64 from ubi-8-baseos-rpms
19.65  Problem 2: conflicting requests
19.65   - nothing provides glibc = 2.28-236.el8_9.12 needed by glibc-locale-source-2.28-236.el8_9.12.x86_64 from ubi-8-baseos-rpms
19.65 (try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

```

### Che version

next (development version)

### Steps to reproduce

1. Clone https://github.com/eclipse-che/che-plugin-registry
2. Try to build `./build.sh`

### Expected behavior

no errors at the build

### Runtime

OpenShift

### Installation method

chectl/latest

### Environment

Linux

**Comment by svor** [comment] 2024-05-07 11:07
similar problem with upstream [UDI build](https://github.com/devfile/developer-images/actions/runs/8966779944/job/24670229942?pr=171):
```
 cannot install both glibc-2.28-236.el8_9.13.x86_64 from ubi-8-baseos-rpms and glibc-2.28-236.el8_9.12.x86_64 from @System
9.819   - cannot install the best update candidate for package glibc-minimal-langpack-2.28-236.el8_9.12.x86_64
9.819   - cannot install the best update candidate for package glibc-2.28-236.el8_9.12.x86_64
9.819  Problem 2: problem with installed package glibc-minimal-langpack-2.28-236.el8_9.12.x86_64
```

**Comment by mkuznyetsov** [comment] 2024-05-08 08:45
plugin registry seems to be building again.
as I am unable to reproduce it anymore, I would close it, until it is reported to be happening again

**Closed as completed by mkuznyetsov** 2024-05-08 08:45 UTC
Labels: kind/bug, area/plugin-registry, team/A
