### ISSUE TITLE
It is not possible to push to eclipse-che/... repositories when oauth2 is configured

### ISSUE THREAD

**Issue by svor** [eclipse/che#22727] opened 2023-12-08 13:47 UTC
### Is your task related to a problem? Please describe

In my dogfooding account I was authorized to GitHub using OAuth2. And I wasn't able to push to remote https://github.com/eclipse-che/che-devfile-registry using dogfooding instance, I think it's about all repositories from https://github.com/eclipse-che/

After configuring a PAT, it wasn't applied: in devworkspace-merged-git-credentials secret I only see oauth2 credential but a credential from my PAT was absent. When I remove all secrets except my PAT, it was applied and I was able to push to the remote branch.

### Describe the solution you'd like

Maybe it also makes sense to extend OAuth scopes by adding write access: https://github.com/eclipse-che/che-server/blob/main/wsmaster/che-core-api-factory-github-common/src/main/java/org/eclipse/che/api/factory/server/github/AbstractGithubPersonalAccessTokenFetcher.java#L50

**Comment by vinokurig** [comment] 2024-02-06 13:53
Expanding the oauth scopes did not solve the issue. This is caused by restrictions on organisation level: https://docs.github.com/en/organizations/managing-oauth-access-to-your-organizations-data/about-oauth-app-access-restrictions

**Comment by svor** [comment] 2024-02-07 08:32
@vinokurig have you investigated the use case described in the description:
```
After configuring a PAT, it wasn't applied: in devworkspace-merged-git-credentials secret I only see oauth2 credential but a credential from my PAT was absent. When I remove all secrets except my PAT, it was applied and I was able to push to the remote branch.
``` 
Is it expected that the PAT wasn't applied from the beginning?

**Comment by svor** [comment] 2024-02-08 10:51
@vinokurig thank you for the investigation. I think it's not obvious for users why the PAT wasn't applied, maybe it should be documented.

**Comment by vitaliy-guliy** [comment] 2024-02-12 15:35
On the dogfooding I can push to che-code, on the developer sandbox I cannot.
But on the developer sandbox I can easily push to my fork of che-code.

**Comment by vinokurig** [comment] 2024-02-14 12:26
Closing this in favour of https://github.com/eclipse/che/issues/22821

**Closed as completed** 2024-02-14 12:27 UTC
Labels: kind/bug, severity/P1, team/A, area/dogfooding, area/git/oauth-services
