### ISSUE TITLE
GitLab Server personal access token failed to add to user preferences in Dashboard because it is was considered as not valid

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse/che#22275] opened 2023-06-07 16:54 UTC
### Describe the bug

https://gitlab.cee.redhat.com/ personal access token hasn't been added to the User Preferences

### Che version

next (development version)

### Steps to reproduce

1. Deploy Eclipse Che Next behind RH VPN.
2. Go to Dashboard > User Preferences > Personal Access Token, and try to add personal access token of https://gitlab.cee.redhat.com

[screencast-gitlab-pat-2023.06.07-19_44_21.webm](https://github.com/eclipse/che/assets/1197777/95546531-d03d-45e3-bc29-670e6e319c91)

There was `Token "gitlab.cee.redhat.com" was not added because it is not valid.` error message shown:
![Screenshot from 2023-06-07 19-45-35](https://github.com/eclipse/che/assets/1197777/08db12f8-16d4-447c-85e6-9d6b43e82183)

I have successfully created workspace from a factory URL after adding PAT manually.
Also, it's interesting that che-server had returned 200 OK response, but personal access token was not created in user namespace:
![Screenshot from 2023-06-12 15-43-30](https://github.com/eclipse/che/assets/1197777/51e6548d-8525-427d-acb5-a1c38b46c7bc)
![Screenshot from 2023-06-12 15-44-39](https://github.com/eclipse/che/assets/1197777/863f8cc3-f5e4-4905-baf5-6b64d56359cd)

### Expected behavior

GitLab Server PAT is added successfully to Dashboard.

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

Linux

### Additional context
I was able to add PAT manually as described in the doc https://www.eclipse.org/che/docs/stable/end-user-guide/using-a-git-provider-access-token/

User Preferences page displayed the token after that:
![Screenshot from 2023-06-09 22-28-26](https://github.com/eclipse/che/assets/1197777/59bd3378-ff03-401a-af5f-b1874ae9f276)

The flow: **che-dashboard** requests namespace provision as it triggers tokens validation, and then check secret is existed  after requiest: https://github.com/eclipse-che/che-dashboard/blob/5da6c4a0da735a8f303b39ea74f21ad27e6462b7/packages/dashboard-frontend/src/store/PersonalAccessToken/index.ts#L114-L159

This indirect validation looks a little bit complicated, IMHO.
"Not valid" token is too vague error message, and rather misleading then helpful.

Another solution: add API method to che-server which will validate token and return meaningful error message from git-provider to show it in Dashboard.

**Comment by vinokurig** [comment] 2023-07-11 12:47
@dmytro-ndp 
I managed to add a `gitlab.cee.redhat.com`  PAT from the Dashboard popup without any issues:
![screenshot-eclipse-che apps ocp413-dnochev crw-qe com-2023 07 11-15_38_56](https://github.com/eclipse/che/assets/7668752/9bf99c49-9b93-42f5-86e5-e07fd60e4111)
Please double check the username and the token string.

**Comment by vinokurig** [comment] 2023-07-24 07:34
@dmytro-ndp any updates?

**Comment by ibuziuk** [comment] 2023-07-25 13:46
@dmytro-ndp please, review before the planning session so that we could prioritize / close

**Comment by dmytro-ndp** [comment] 2023-07-25 14:35
@vinokurig : I had checked GitLab account token several times when investigated the problem, and the token worked when setup PAT flow manually following https://www.eclipse.org/che/docs/stable/end-user-guide/using-a-git-provider-access-token/

**Comment by ibuziuk** [comment] 2023-07-26 13:06
Closing as Can't Reproduce

**Closed as completed by ibuziuk** 2023-07-26 13:06 UTC
Labels: kind/bug, severity/P1, area/dashboard, team/A, area/dogfooding
