### ISSUE TITLE
Update Dependency Analytics plugin to the newest version 

### ISSUE THREAD

**Issue by svor** [eclipse/che#21371] opened 2022-05-04 13:35 UTC
### Is your task related to a problem? Please describe

Currently the version of Dependency Analytics plugin is [0.2.1](https://github.com/eclipse-che/che-plugin-registry/blob/main/che-theia-plugins.yaml#L287) but it's already outdated. The latest released version is [0.3.5](https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/releases/tag/0.3.5). 

   

### Describe the solution you'd like

Let's try to update Dependency Analytics plugin to the latest version and check if everything works with current state of che-theia API

**Comment by nickboldt** [comment] 2022-05-04 15:06
dupe of https://github.com/eclipse/che/issues/21372; closing as the other has more info/details/link to downstream

**Closed as completed by nickboldt** 2022-05-04 15:06 UTC
Labels: kind/task, severity/P2, area/plugins
